
/**
 * Vision-to-Code Configuration.
 */
export interface VisionConfig {
  apiKey?: string;
  model?: 'gpt-4o' | 'gemini-1.5-pro' | 'claude-3-5-sonnet';
  framework?: 'react' | 'vue' | 'solid' | 'html';
  styling?: 'tailwind' | 'css' | 'styled-components';
}

/**
 * Vision-to-Code Generator.
 * Orchestrates the conversion of UI screenshots to code via VLM.
 */
export class VisionCode {
  static SYSTEM_PROMPT = `You are an expert frontend engineer. 
    Analyze the provided UI screenshot and replicate it pixel-perfectly.
    Use semantic HTML and modern best practices.`;

  static async generate(imageBase64: string, config: VisionConfig = {}): Promise<string> {
    const framework = config.framework || 'react';
    const styling = config.styling || 'tailwind';

    const userPrompt = `Convert this UI image into ${framework} code using ${styling}. 
        Return ONLY the code block. Do not include explanations.`;

    if (!config.apiKey) {
      console.warn('VisionCode: No API Key provided. Returning High-Fidelity Mock.');
      return this.generateMock(framework);
    }

    // Implementation for real API call would go here (fetch to OpenAI/Anthropic/Gemini)
    // Returning a placeholder for the "Connected" state
    return `/* Real API Call Wrapper Implementation */
// POST https://api.openai.com/v1/chat/completions
// { model: "${config.model || 'gpt-4o'}", messages: [...] }
`;
  }

  /**
   * Generates a structural mock when no API is available.
   * This ensures the function always returns valid code for testing/demo.
   */
  private static generateMock(framework: string): string {
    const isReact = framework === 'react';
    const className = isReact ? 'className' : 'class';

    return `
${isReact ? "import React from 'react';" : ''}

export default function GeneratedComponent() {
  return (
    <div ${className}="min-h-screen bg-gray-50 font-sans">
      <header ${className}="bg-white shadow p-4 flex justify-between items-center">
        <h1 ${className}="text-xl font-bold text-gray-800">Vision Generated</h1>
        <nav ${className}="space-x-4">
          <a href="#" ${className}="text-blue-600">Home</a>
          <a href="#" ${className}="text-gray-600">Features</a>
        </nav>
      </header>
      
      <main ${className}="max-w-4xl mx-auto mt-10 p-6 bg-white rounded-lg shadow">
        <div ${className}="prose">
          <h2>Detected UI Structure</h2>
          <p>This component was generated by PhilJS Vision (Mock Mode).</p>
          <div ${className}="grid grid-cols-3 gap-4 mt-6">
             <div ${className}="p-4 border rounded bg-gray-100">Feature A</div>
             <div ${className}="p-4 border rounded bg-gray-100">Feature B</div>
             <div ${className}="p-4 border rounded bg-gray-100">Feature C</div>
          </div>
        </div>
      </main>
    </div>
  );
}
`;
  }
}

export const uiFromImage = VisionCode.generate;
