export { signal, memo, linkedSignal, resource, effect, batch, untrack, onCleanup, createRoot } from "./signals.js";
export type { Signal, Memo, LinkedSignal, Resource, EffectCleanup } from "./signals.js";
export { jsx, jsxs, jsxDEV, Fragment, createElement, isJSXElement } from "./jsx-runtime.js";
export type { JSXElement, VNode } from "./jsx-runtime.js";
export { renderToString, renderToStream } from "./render-to-string.js";
export { hydrate, render } from "./hydrate.js";
export { initResumability, getResumableState, serializeResumableState, resume, resumable, registerHandler, registerState } from "./resumability.js";
export type { SerializedHandler, ResumableState } from "./resumability.js";
export { createQuery, createMutation, queryCache, invalidateQueries, prefetchQuery } from "./data-layer.js";
export type { QueryOptions, QueryResult, MutationOptions, MutationResult } from "./data-layer.js";
export { createContext, useContext, createSignalContext, createReducerContext, // @deprecated - Use signal() and createSignalContext() instead
combineProviders, createThemeContext } from "./context.js";
export type { Context } from "./context.js";
export { createAnimatedValue, easings, FLIPAnimator, attachGestures, createParallax } from "./animation.js";
export type { AnimationOptions, SpringConfig, AnimatedValue, GestureHandlers } from "./animation.js";
export { I18nProvider, useI18n, useTranslation, TranslationExtractor, AITranslationService, createLocaleMiddleware } from "./i18n.js";
export type { Locale, Translations, I18nConfig, FormatOptions } from "./i18n.js";
export { ErrorBoundary, setupGlobalErrorHandler, errorRecovery } from "./error-boundary.js";
export type { ErrorInfo, ErrorBoundaryProps, ErrorCategory, ErrorSuggestion } from "./error-boundary.js";
export { generateServiceWorker, registerServiceWorker, unregisterServiceWorkers, skipWaitingAndClaim, defaultCacheRules } from "./service-worker.js";
export type { CacheStrategy, CacheRule, ServiceWorkerConfig } from "./service-worker.js";
export { performanceBudgets, PerformanceBudgetManager, performanceBudgetPlugin } from "./performance-budgets.js";
export type { PerformanceBudget, RouteMetrics, RegressionReport } from "./performance-budgets.js";
export { costTracker, CostTracker } from "./cost-tracking.js";
export type { CostMetrics, CostEstimate, CloudProvider } from "./cost-tracking.js";
export { usageAnalytics, UsageAnalytics } from "./usage-analytics.js";
export type { ComponentUsage, DeadCodeReport, OptimizationSuggestion } from "./usage-analytics.js";
export { Ok, Err, isOk, isErr, isResult, map, mapErr, andThen, unwrap, unwrapOr, matchResult, } from "./result.js";
export type { Result } from "./result.js";
export { useForm, v as validators, createField } from "./forms.js";
export type { FormApi, FormSchema, FieldSchema, ValidationRule, ValidationError, FormState, UseFormOptions, FieldProps } from "./forms.js";
export { configureA11y, getA11yConfig, enhanceWithAria, validateHeadingHierarchy, getHeadingWarnings, resetHeadingTracker, getContrastRatio, validateColorContrast, auditAccessibility, startA11yMonitoring, addSkipLink, announceToScreenReader, createLoadingState, createFocusManager, KeyboardNavigator } from "./accessibility.js";
export type { A11yConfig, A11yWarning, A11yReport, FocusManager } from "./accessibility.js";
export { ABTestEngine, initABTesting, getABTestEngine, useExperiment, ABTest, useFeatureFlag, createMultivariateTest, calculateSignificance } from "./ab-testing.js";
export type { Experiment, Variant, TargetingRules, User, ExperimentAssignment, ExperimentEvent, ExperimentResults, VariantResults, ABTestConfig } from "./ab-testing.js";
//# sourceMappingURL=index.d.ts.map