/**
 * PhilJS Migrate - Report Generator
 */
import * as fs from 'fs/promises';
export async function generateReport(result, analysis, outputPath) {
    const report = buildReport(result, analysis);
    await fs.writeFile(outputPath, report);
}
function buildReport(result, analysis) {
    const timestamp = new Date().toISOString();
    return `# PhilJS Migration Report

Generated: ${timestamp}

## Project Analysis

| Metric | Value |
|--------|-------|
| Framework | ${analysis.framework} ${analysis.version || ''} |
| TypeScript | ${analysis.typescript ? 'Yes' : 'No'} |
| Package Manager | ${analysis.packageManager} |
| Total Files | ${analysis.complexity.totalFiles} |
| Component Files | ${analysis.complexity.componentFiles} |
| Lines of Code | ${analysis.complexity.linesOfCode} |

### Detected Features

- **State Management**: ${analysis.features.stateManagement.join(', ') || 'None detected'}
- **Routing**: ${analysis.features.router ? 'Yes' : 'No'}
- **CSS Framework**: ${analysis.features.cssFramework.join(', ') || 'None detected'}
- **Testing**: ${analysis.features.testingFramework.join(', ') || 'None detected'}

## Migration Summary

| Metric | Count |
|--------|-------|
| Files Processed | ${result.filesProcessed} |
| Files Transformed | ${result.filesTransformed} |
| Errors | ${result.errors.length} |
| Warnings | ${result.warnings.length} |
| Manual Review Items | ${result.manualReviewNeeded.length} |

### Status: ${result.success ? '✅ Success' : '❌ Failed'}

---

## Errors

${result.errors.length === 0 ? 'No errors occurred during migration.' : ''}

${result.errors.map(error => `
### ${error.file}${error.line ? `:${error.line}` : ''}

**Code**: \`${error.code}\`

${error.message}
`).join('\n')}

---

## Warnings

${result.warnings.length === 0 ? 'No warnings generated.' : ''}

${result.warnings.map((warning, i) => `
${i + 1}. **${warning.file}**${warning.line ? ` (line ${warning.line})` : ''}
   - ${warning.message}
   ${warning.suggestion ? `\n   - **Suggestion**: ${warning.suggestion}` : ''}
`).join('\n')}

---

## Manual Review Required

The following items need manual review and may require code adjustments:

${result.manualReviewNeeded.length === 0 ? 'No items require manual review.' : ''}

${result.manualReviewNeeded.map((item, i) => `
### ${i + 1}. ${item.type} - ${item.file}:${item.line}

**Description**: ${item.description}

**Original Code**:
\`\`\`
${item.originalCode}
\`\`\`

${item.suggestedCode ? `**Suggested Code**:
\`\`\`
${item.suggestedCode}
\`\`\`
` : ''}
`).join('\n')}

---

## Dependency Mapping

The following dependencies can be replaced with PhilJS equivalents:

| Original | PhilJS Equivalent |
|----------|-------------------|
${analysis.dependencies
        .filter(d => d.philjsEquivalent)
        .map(d => `| ${d.name}@${d.version} | ${d.philjsEquivalent} |`)
        .join('\n')}

---

## Next Steps

1. **Review transformed files** - Check the converted code for correctness
2. **Address manual review items** - Update code that couldn't be automatically converted
3. **Update imports** - Ensure all imports point to PhilJS packages
4. **Test thoroughly** - Run your test suite and fix any failures
5. **Update build configuration** - Update Vite/webpack config if needed

### Signal Usage Reminders

After migration, remember:
- Use \`.get()\` to read signal values
- Use \`.set(newValue)\` to update signal values
- Use \`.update(fn)\` for updates based on previous value
- Effects auto-track dependencies - no dependency arrays needed
- Computed values are cached and update automatically

### Helpful Resources

- [PhilJS Documentation](https://philjs.dev/docs)
- [Migration Guide](https://philjs.dev/docs/migration)
- [Signal Patterns](https://philjs.dev/docs/signals)
- [PhilJS vs ${analysis.framework}](https://philjs.dev/docs/comparison/${analysis.framework})

---

*Report generated by PhilJS Migration Tool v1.0.0*
`;
}
//# sourceMappingURL=report.js.map