/**
 * GraphQL Code Generation Tests
 */

import { describe, it, expect } from 'vitest';
import {
  createCodegen,
  createBatchCodegen,
  extractOperationInfo,
  extractFragmentInfo,
} from './codegen-enhanced';
import { gql } from './index';

describe('GraphQLCodegen', () => {
  it('should create a code generator', () => {
    const codegen = createCodegen({
      schema: 'https://api.example.com/graphql',
      documents: ['src/**/*.graphql'],
      outputDir: 'src/generated',
    });

    expect(codegen).toBeDefined();
  });

  it('should generate query types', () => {
    const codegen = createCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    const query = gql`
      query GetUsers {
        users {
          id
          name
        }
      }
    `;

    const types = codegen.generateQueryTypes('GetUsers', query);

    expect(types).toContain('GetUsersQuery');
    expect(types).toContain('GetUsersVariables');
    expect(types).toContain('useGetUsersQuery');
  });

  it('should generate mutation types', () => {
    const codegen = createCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    const mutation = gql`
      mutation CreateUser($name: String!) {
        createUser(name: $name) {
          id
          name
        }
      }
    `;

    const types = codegen.generateMutationTypes('CreateUser', mutation);

    expect(types).toContain('CreateUserMutation');
    expect(types).toContain('CreateUserVariables');
    expect(types).toContain('useCreateUserMutation');
  });

  it('should generate mutation types with optimistic response', () => {
    const codegen = createCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    const mutation = gql`
      mutation CreateUser($name: String!) {
        createUser(name: $name) {
          id
          name
        }
      }
    `;

    const types = codegen.generateMutationTypes('CreateUser', mutation, {
      generateOptimistic: true,
    });

    expect(types).toContain('CreateUserOptimisticResponse');
  });

  it('should generate subscription types', () => {
    const codegen = createCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    const subscription = gql`
      subscription OnMessage {
        newMessage {
          id
          text
        }
      }
    `;

    const types = codegen.generateSubscriptionTypes('OnMessage', subscription);

    expect(types).toContain('OnMessageSubscription');
    expect(types).toContain('OnMessageVariables');
    expect(types).toContain('useOnMessageSubscription');
  });

  it('should generate fragment types', () => {
    const codegen = createCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    const fragment = gql`
      fragment UserFields on User {
        id
        name
        email
      }
    `;

    const types = codegen.generateFragmentTypes('UserFields', 'User', fragment);

    expect(types).toContain('UserFieldsFragment');
    expect(types).toContain('UserFieldsFragmentDoc');
  });

  it('should generate complete types file', () => {
    const codegen = createCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    const operations = [
      {
        name: 'GetUsers',
        type: 'query' as const,
        document: gql`query GetUsers { users { id } }`,
      },
      {
        name: 'CreateUser',
        type: 'mutation' as const,
        document: gql`mutation CreateUser { createUser { id } }`,
      },
      {
        name: 'OnMessage',
        type: 'subscription' as const,
        document: gql`subscription OnMessage { newMessage { id } }`,
      },
    ];

    const fragments = [
      {
        name: 'UserFields',
        on: 'User',
        document: gql`fragment UserFields on User { id name }`,
      },
    ];

    const code = codegen.generateTypesFile(operations, fragments);

    expect(code).toContain('Generated by PhilJS GraphQL Codegen');
    expect(code).toContain('GetUsersQuery');
    expect(code).toContain('CreateUserMutation');
    expect(code).toContain('OnMessageSubscription');
    expect(code).toContain('UserFieldsFragment');
  });
});

describe('BatchCodegen', () => {
  it('should create a batch code generator', () => {
    const batchCodegen = createBatchCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    expect(batchCodegen).toBeDefined();
  });

  it('should add operations', () => {
    const batchCodegen = createBatchCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    batchCodegen.addOperation(
      'GetUsers',
      'query',
      gql`query GetUsers { users { id } }`
    );

    batchCodegen.addOperation(
      'CreateUser',
      'mutation',
      gql`mutation CreateUser { createUser { id } }`
    );

    const code = batchCodegen.generate();

    expect(code).toContain('GetUsersQuery');
    expect(code).toContain('CreateUserMutation');
  });

  it('should add fragments', () => {
    const batchCodegen = createBatchCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    batchCodegen.addFragment(
      'UserFields',
      'User',
      gql`fragment UserFields on User { id name }`
    );

    const code = batchCodegen.generate();

    expect(code).toContain('UserFieldsFragment');
  });

  it('should clear operations and fragments', () => {
    const batchCodegen = createBatchCodegen({
      schema: 'https://api.example.com/graphql',
      documents: [],
      outputDir: 'src/generated',
    });

    batchCodegen.addOperation(
      'GetUsers',
      'query',
      gql`query GetUsers { users { id } }`
    );

    batchCodegen.clear();

    const code = batchCodegen.generate();

    // Should generate minimal code without operations
    expect(code).toContain('Generated by PhilJS GraphQL Codegen');
    expect(code).not.toContain('GetUsersQuery');
  });
});

describe('extractOperationInfo', () => {
  it('should extract query info', () => {
    const query = gql`
      query GetUsers {
        users {
          id
        }
      }
    `;

    const info = extractOperationInfo(query);

    expect(info).toEqual({
      type: 'query',
      name: 'GetUsers',
    });
  });

  it('should extract mutation info', () => {
    const mutation = gql`
      mutation CreateUser {
        createUser {
          id
        }
      }
    `;

    const info = extractOperationInfo(mutation);

    expect(info).toEqual({
      type: 'mutation',
      name: 'CreateUser',
    });
  });

  it('should extract subscription info', () => {
    const subscription = gql`
      subscription OnMessage {
        newMessage {
          id
        }
      }
    `;

    const info = extractOperationInfo(subscription);

    expect(info).toEqual({
      type: 'subscription',
      name: 'OnMessage',
    });
  });

  it('should return null for invalid operation', () => {
    const invalid = 'not a valid operation';

    const info = extractOperationInfo(invalid);

    expect(info).toBeNull();
  });
});

describe('extractFragmentInfo', () => {
  it('should extract fragment info', () => {
    const fragment = gql`
      fragment UserFields on User {
        id
        name
      }
    `;

    const info = extractFragmentInfo(fragment);

    expect(info).toEqual({
      name: 'UserFields',
      on: 'User',
    });
  });

  it('should return null for invalid fragment', () => {
    const invalid = 'not a valid fragment';

    const info = extractFragmentInfo(invalid);

    expect(info).toBeNull();
  });
});
