
export interface Tool {
    name: string;
    description: string;
    execute: (input: any) => Promise<any>;
}

export interface AgentConfig {
    model: 'gpt-4o' | 'claude-3-5-sonnet' | 'gemini-1.5-pro';
    temperature?: number;
    systemPrompt?: string;
    tools?: Tool[];
}

export class Agent {
    constructor(private config: AgentConfig) { }

    async run(prompt: string): Promise<string> {
        console.log(`Agent (${this.config.model}): Thinking specifically about "${prompt}"...`);

        // 1. Tool Selection Simulation
        if (this.config.tools?.length && prompt.includes('search')) {
            const tool = this.config.tools.find(t => t.name === 'search');
            if (tool) {
                console.log(`Agent: Decided to use tool "${tool.name}"`);
                const result = await tool.execute({ query: prompt });
                return `Based on search results: ${JSON.stringify(result)}`;
            }
        }

        // 2. Direct LLM Response Simulation
        return `AI Response to: "${prompt}" (Generated by ${this.config.model})`;
    }

    async stream(prompt: string, onChunk: (chunk: string) => void): Promise<void> {
        const response = await this.run(prompt);
        const words = response.split(' ');

        for (const word of words) {
            await new Promise(r => setTimeout(r, 50)); // Simulate token stream
            onChunk(word + ' ');
        }
    }
}
