AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PhilJS on AWS Lambda Example

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs20.x

Resources:
  PhilJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws/lambda/
      Handler: index.handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
