/**
 * Built-in Templates for the Visual Builder
 *
 * Provides a comprehensive set of pre-designed templates for common layouts.
 */

import type { Template } from './TemplateSystem.js';

// ============================================================================
// Dashboard Templates
// ============================================================================

export const dashboardSidebar: Template = {
  id: 'template_dashboard_sidebar',
  name: 'Dashboard with Sidebar',
  description: 'A dashboard layout with sidebar navigation and content area',
  category: 'dashboard',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['dashboard', 'sidebar', 'admin', 'layout'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Dashboard Layout',
      props: {},
      styles: {
        display: 'flex',
        minHeight: { value: 100, unit: 'vh' },
        backgroundColor: '#f1f5f9',
      },
      children: ['sidebar', 'main'],
      parentId: null,
      events: [],
    },
    'sidebar': {
      id: 'sidebar',
      type: 'Frame',
      name: 'Sidebar',
      props: {},
      styles: {
        width: { value: 250, unit: 'px' },
        backgroundColor: '#1e293b',
        padding: { value: 16, unit: 'px' },
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 8, unit: 'px' },
      },
      children: ['sidebarLogo', 'sidebarNav'],
      parentId: 'root',
      events: [],
    },
    'sidebarLogo': {
      id: 'sidebarLogo',
      type: 'Heading',
      name: 'Logo',
      props: { content: 'Dashboard', level: 'h2' },
      styles: {
        color: '#ffffff',
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 700,
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'sidebar',
      events: [],
    },
    'sidebarNav': {
      id: 'sidebarNav',
      type: 'Stack',
      name: 'Navigation',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 4, unit: 'px' },
      },
      children: ['navHome', 'navAnalytics', 'navSettings'],
      parentId: 'sidebar',
      events: [],
    },
    'navHome': {
      id: 'navHome',
      type: 'NavItem',
      name: 'Home',
      props: { label: 'Home', active: true },
      styles: {
        padding: { value: 12, unit: 'px' },
        borderRadius: { value: 6, unit: 'px' },
        backgroundColor: '#334155',
        color: '#ffffff',
        cursor: 'pointer',
      },
      children: [],
      parentId: 'sidebarNav',
      events: [],
    },
    'navAnalytics': {
      id: 'navAnalytics',
      type: 'NavItem',
      name: 'Analytics',
      props: { label: 'Analytics' },
      styles: {
        padding: { value: 12, unit: 'px' },
        borderRadius: { value: 6, unit: 'px' },
        color: '#94a3b8',
        cursor: 'pointer',
      },
      children: [],
      parentId: 'sidebarNav',
      events: [],
    },
    'navSettings': {
      id: 'navSettings',
      type: 'NavItem',
      name: 'Settings',
      props: { label: 'Settings' },
      styles: {
        padding: { value: 12, unit: 'px' },
        borderRadius: { value: 6, unit: 'px' },
        color: '#94a3b8',
        cursor: 'pointer',
      },
      children: [],
      parentId: 'sidebarNav',
      events: [],
    },
    'main': {
      id: 'main',
      type: 'Frame',
      name: 'Main Content',
      props: {},
      styles: {
        flex: '1',
        padding: { value: 24, unit: 'px' },
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 24, unit: 'px' },
      },
      children: ['header', 'statsGrid', 'content'],
      parentId: 'root',
      events: [],
    },
    'header': {
      id: 'header',
      type: 'HStack',
      name: 'Header',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      children: ['headerTitle', 'headerActions'],
      parentId: 'main',
      events: [],
    },
    'headerTitle': {
      id: 'headerTitle',
      type: 'Heading',
      name: 'Page Title',
      props: { content: 'Dashboard', level: 'h1' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'headerActions': {
      id: 'headerActions',
      type: 'HStack',
      name: 'Actions',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 8, unit: 'px' },
      },
      children: ['actionBtn'],
      parentId: 'header',
      events: [],
    },
    'actionBtn': {
      id: 'actionBtn',
      type: 'Button',
      name: 'Add New',
      props: { label: '+ Add New', variant: 'primary' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 20, unit: 'px' },
        paddingRight: { value: 20, unit: 'px' },
        backgroundColor: '#2563eb',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'headerActions',
      events: [],
    },
    'statsGrid': {
      id: 'statsGrid',
      type: 'Grid',
      name: 'Stats Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: { value: 16, unit: 'px' },
      },
      children: ['stat1', 'stat2', 'stat3', 'stat4'],
      parentId: 'main',
      events: [],
    },
    'stat1': {
      id: 'stat1',
      type: 'Card',
      name: 'Stat Card 1',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat1Label', 'stat1Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat1Label': {
      id: 'stat1Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Total Users' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat1',
      events: [],
    },
    'stat1Value': {
      id: 'stat1Value',
      type: 'Text',
      name: 'Value',
      props: { content: '12,543' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat1',
      events: [],
    },
    'stat2': {
      id: 'stat2',
      type: 'Card',
      name: 'Stat Card 2',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat2Label', 'stat2Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat2Label': {
      id: 'stat2Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Revenue' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat2',
      events: [],
    },
    'stat2Value': {
      id: 'stat2Value',
      type: 'Text',
      name: 'Value',
      props: { content: '$45,234' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat2',
      events: [],
    },
    'stat3': {
      id: 'stat3',
      type: 'Card',
      name: 'Stat Card 3',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat3Label', 'stat3Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat3Label': {
      id: 'stat3Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Orders' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat3',
      events: [],
    },
    'stat3Value': {
      id: 'stat3Value',
      type: 'Text',
      name: 'Value',
      props: { content: '1,234' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat3',
      events: [],
    },
    'stat4': {
      id: 'stat4',
      type: 'Card',
      name: 'Stat Card 4',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat4Label', 'stat4Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat4Label': {
      id: 'stat4Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Conversion' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat4',
      events: [],
    },
    'stat4Value': {
      id: 'stat4Value',
      type: 'Text',
      name: 'Value',
      props: { content: '3.24%' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat4',
      events: [],
    },
    'content': {
      id: 'content',
      type: 'Card',
      name: 'Content Area',
      props: {},
      styles: {
        flex: '1',
        backgroundColor: '#ffffff',
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['contentTitle', 'contentPlaceholder'],
      parentId: 'main',
      events: [],
    },
    'contentTitle': {
      id: 'contentTitle',
      type: 'Heading',
      name: 'Section Title',
      props: { content: 'Recent Activity', level: 'h3' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'content',
      events: [],
    },
    'contentPlaceholder': {
      id: 'contentPlaceholder',
      type: 'Paragraph',
      name: 'Placeholder',
      props: { content: 'Add your content here. This could be a table, chart, or list.' },
      styles: {
        color: '#64748b',
      },
      children: [],
      parentId: 'content',
      events: [],
    },
  },
};

// ============================================================================
// Landing Page Templates
// ============================================================================

export const landingPageSimple: Template = {
  id: 'template_landing_simple',
  name: 'Simple Landing Page',
  description: 'A clean landing page with hero, features, and footer',
  category: 'landing',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['landing', 'marketing', 'hero', 'features'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Landing Page',
      props: {},
      styles: {
        minHeight: { value: 100, unit: 'vh' },
        backgroundColor: '#ffffff',
      },
      children: ['navbar', 'hero', 'features', 'footer'],
      parentId: null,
      events: [],
    },
    'navbar': {
      id: 'navbar',
      type: 'Nav',
      name: 'Navigation Bar',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 64, unit: 'px' },
        paddingRight: { value: 64, unit: 'px' },
        borderBottom: '1px solid #e5e7eb',
      },
      children: ['navLogo', 'navLinks', 'navCta'],
      parentId: 'root',
      events: [],
    },
    'navLogo': {
      id: 'navLogo',
      type: 'Heading',
      name: 'Logo',
      props: { content: 'Brand', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'navbar',
      events: [],
    },
    'navLinks': {
      id: 'navLinks',
      type: 'HStack',
      name: 'Nav Links',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 32, unit: 'px' },
      },
      children: ['navLink1', 'navLink2', 'navLink3'],
      parentId: 'navbar',
      events: [],
    },
    'navLink1': {
      id: 'navLink1',
      type: 'Link',
      name: 'Features',
      props: { label: 'Features', href: '#features' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'navLinks',
      events: [],
    },
    'navLink2': {
      id: 'navLink2',
      type: 'Link',
      name: 'Pricing',
      props: { label: 'Pricing', href: '#pricing' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'navLinks',
      events: [],
    },
    'navLink3': {
      id: 'navLink3',
      type: 'Link',
      name: 'About',
      props: { label: 'About', href: '#about' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'navLinks',
      events: [],
    },
    'navCta': {
      id: 'navCta',
      type: 'Button',
      name: 'Get Started',
      props: { label: 'Get Started', variant: 'primary' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 20, unit: 'px' },
        paddingRight: { value: 20, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'navbar',
      events: [],
    },
    'hero': {
      id: 'hero',
      type: 'Frame',
      name: 'Hero Section',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: { value: 80, unit: 'px' },
        paddingTop: { value: 120, unit: 'px' },
        paddingBottom: { value: 120, unit: 'px' },
        backgroundColor: '#f8fafc',
      },
      children: ['heroTitle', 'heroSubtitle', 'heroButtons'],
      parentId: 'root',
      events: [],
    },
    'heroTitle': {
      id: 'heroTitle',
      type: 'Heading',
      name: 'Hero Title',
      props: { content: 'Build Something Amazing', level: 'h1' },
      styles: {
        fontSize: { value: 56, unit: 'px' },
        fontWeight: 800,
        color: '#0f172a',
        marginBottom: { value: 24, unit: 'px' },
        lineHeight: { value: 1.1, unit: 'none' },
      },
      children: [],
      parentId: 'hero',
      events: [],
    },
    'heroSubtitle': {
      id: 'heroSubtitle',
      type: 'Paragraph',
      name: 'Hero Subtitle',
      props: { content: 'The fastest way to build production-ready applications. Start building in minutes with our intuitive tools and components.' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        color: '#64748b',
        maxWidth: { value: 600, unit: 'px' },
        marginBottom: { value: 40, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'hero',
      events: [],
    },
    'heroButtons': {
      id: 'heroButtons',
      type: 'HStack',
      name: 'Hero Buttons',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 16, unit: 'px' },
      },
      children: ['heroPrimaryBtn', 'heroSecondaryBtn'],
      parentId: 'hero',
      events: [],
    },
    'heroPrimaryBtn': {
      id: 'heroPrimaryBtn',
      type: 'Button',
      name: 'Primary CTA',
      props: { label: 'Start Free Trial', variant: 'primary' },
      styles: {
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 32, unit: 'px' },
        paddingRight: { value: 32, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        fontWeight: 600,
        fontSize: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'heroButtons',
      events: [],
    },
    'heroSecondaryBtn': {
      id: 'heroSecondaryBtn',
      type: 'Button',
      name: 'Secondary CTA',
      props: { label: 'Watch Demo', variant: 'outline' },
      styles: {
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 32, unit: 'px' },
        paddingRight: { value: 32, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#0f172a',
        border: '2px solid #0f172a',
        borderRadius: { value: 8, unit: 'px' },
        fontWeight: 600,
        fontSize: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'heroButtons',
      events: [],
    },
    'features': {
      id: 'features',
      type: 'Frame',
      name: 'Features Section',
      props: {},
      styles: {
        padding: { value: 80, unit: 'px' },
        paddingLeft: { value: 64, unit: 'px' },
        paddingRight: { value: 64, unit: 'px' },
      },
      children: ['featuresTitle', 'featuresGrid'],
      parentId: 'root',
      events: [],
    },
    'featuresTitle': {
      id: 'featuresTitle',
      type: 'Heading',
      name: 'Features Title',
      props: { content: 'Everything you need', level: 'h2' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        textAlign: 'center',
        marginBottom: { value: 48, unit: 'px' },
      },
      children: [],
      parentId: 'features',
      events: [],
    },
    'featuresGrid': {
      id: 'featuresGrid',
      type: 'Grid',
      name: 'Features Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: { value: 32, unit: 'px' },
      },
      children: ['feature1', 'feature2', 'feature3'],
      parentId: 'features',
      events: [],
    },
    'feature1': {
      id: 'feature1',
      type: 'Card',
      name: 'Feature 1',
      props: {},
      styles: {
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 12, unit: 'px' },
        border: '1px solid #e5e7eb',
      },
      children: ['feature1Title', 'feature1Desc'],
      parentId: 'featuresGrid',
      events: [],
    },
    'feature1Title': {
      id: 'feature1Title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Fast Performance', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: [],
      parentId: 'feature1',
      events: [],
    },
    'feature1Desc': {
      id: 'feature1Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Optimized for speed with minimal bundle size and efficient rendering.' },
      styles: {
        color: '#64748b',
        fontSize: { value: 15, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'feature1',
      events: [],
    },
    'feature2': {
      id: 'feature2',
      type: 'Card',
      name: 'Feature 2',
      props: {},
      styles: {
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 12, unit: 'px' },
        border: '1px solid #e5e7eb',
      },
      children: ['feature2Title', 'feature2Desc'],
      parentId: 'featuresGrid',
      events: [],
    },
    'feature2Title': {
      id: 'feature2Title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Easy to Use', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: [],
      parentId: 'feature2',
      events: [],
    },
    'feature2Desc': {
      id: 'feature2Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Intuitive API design that gets you started in minutes, not hours.' },
      styles: {
        color: '#64748b',
        fontSize: { value: 15, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'feature2',
      events: [],
    },
    'feature3': {
      id: 'feature3',
      type: 'Card',
      name: 'Feature 3',
      props: {},
      styles: {
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 12, unit: 'px' },
        border: '1px solid #e5e7eb',
      },
      children: ['feature3Title', 'feature3Desc'],
      parentId: 'featuresGrid',
      events: [],
    },
    'feature3Title': {
      id: 'feature3Title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Fully Customizable', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: [],
      parentId: 'feature3',
      events: [],
    },
    'feature3Desc': {
      id: 'feature3Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Extend and customize everything to match your brand and requirements.' },
      styles: {
        color: '#64748b',
        fontSize: { value: 15, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'feature3',
      events: [],
    },
    'footer': {
      id: 'footer',
      type: 'Frame',
      name: 'Footer',
      props: {},
      styles: {
        padding: { value: 48, unit: 'px' },
        paddingLeft: { value: 64, unit: 'px' },
        paddingRight: { value: 64, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#94a3b8',
        textAlign: 'center',
      },
      children: ['footerText'],
      parentId: 'root',
      events: [],
    },
    'footerText': {
      id: 'footerText',
      type: 'Paragraph',
      name: 'Copyright',
      props: { content: '2025 Your Company. All rights reserved.' },
      styles: {
        color: '#94a3b8',
        fontSize: { value: 14, unit: 'px' },
      },
      children: [],
      parentId: 'footer',
      events: [],
    },
  },
};

// ============================================================================
// Navigation Templates
// ============================================================================

export const navigationHeader: Template = {
  id: 'template_nav_header',
  name: 'Header Navigation',
  description: 'A responsive header with logo, navigation links, and actions',
  category: 'navigation',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['header', 'navigation', 'navbar', 'responsive'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Nav',
      name: 'Header Navigation',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 24, unit: 'px' },
        paddingRight: { value: 24, unit: 'px' },
        backgroundColor: '#ffffff',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
        position: 'sticky',
        top: { value: 0, unit: 'px' },
        zIndex: 100,
      },
      children: ['logo', 'links', 'actions'],
      parentId: null,
      events: [],
    },
    'logo': {
      id: 'logo',
      type: 'HStack',
      name: 'Logo Area',
      props: {},
      styles: {
        display: 'flex',
        alignItems: 'center',
        gap: { value: 8, unit: 'px' },
      },
      children: ['logoText'],
      parentId: 'root',
      events: [],
    },
    'logoText': {
      id: 'logoText',
      type: 'Heading',
      name: 'Logo',
      props: { content: 'Logo', level: 'h3' },
      styles: {
        fontSize: { value: 24, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'logo',
      events: [],
    },
    'links': {
      id: 'links',
      type: 'HStack',
      name: 'Navigation Links',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 32, unit: 'px' },
      },
      children: ['link1', 'link2', 'link3', 'link4'],
      parentId: 'root',
      events: [],
    },
    'link1': {
      id: 'link1',
      type: 'Link',
      name: 'Home',
      props: { label: 'Home', href: '/' },
      styles: {
        color: '#0f172a',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'link2': {
      id: 'link2',
      type: 'Link',
      name: 'Products',
      props: { label: 'Products', href: '/products' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'link3': {
      id: 'link3',
      type: 'Link',
      name: 'Pricing',
      props: { label: 'Pricing', href: '/pricing' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'link4': {
      id: 'link4',
      type: 'Link',
      name: 'Contact',
      props: { label: 'Contact', href: '/contact' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'actions': {
      id: 'actions',
      type: 'HStack',
      name: 'Actions',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 12, unit: 'px' },
      },
      children: ['loginBtn', 'signupBtn'],
      parentId: 'root',
      events: [],
    },
    'loginBtn': {
      id: 'loginBtn',
      type: 'Button',
      name: 'Login',
      props: { label: 'Log In', variant: 'ghost' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 16, unit: 'px' },
        paddingRight: { value: 16, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#64748b',
        fontWeight: 500,
      },
      children: [],
      parentId: 'actions',
      events: [],
    },
    'signupBtn': {
      id: 'signupBtn',
      type: 'Button',
      name: 'Sign Up',
      props: { label: 'Sign Up', variant: 'primary' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 20, unit: 'px' },
        paddingRight: { value: 20, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'actions',
      events: [],
    },
  },
};

// ============================================================================
// Content Templates
// ============================================================================

export const pricingTable: Template = {
  id: 'template_pricing_table',
  name: 'Pricing Table',
  description: 'A three-tier pricing table with features comparison',
  category: 'content',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['pricing', 'table', 'plans', 'comparison'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Pricing Section',
      props: {},
      styles: {
        padding: { value: 64, unit: 'px' },
        backgroundColor: '#f8fafc',
      },
      children: ['title', 'subtitle', 'grid'],
      parentId: null,
      events: [],
    },
    'title': {
      id: 'title',
      type: 'Heading',
      name: 'Section Title',
      props: { content: 'Simple, transparent pricing', level: 'h2' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        textAlign: 'center',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'root',
      events: [],
    },
    'subtitle': {
      id: 'subtitle',
      type: 'Paragraph',
      name: 'Subtitle',
      props: { content: 'Choose the plan that works best for you and your team.' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        color: '#64748b',
        textAlign: 'center',
        marginBottom: { value: 48, unit: 'px' },
      },
      children: [],
      parentId: 'root',
      events: [],
    },
    'grid': {
      id: 'grid',
      type: 'Grid',
      name: 'Pricing Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: { value: 24, unit: 'px' },
        maxWidth: { value: 1000, unit: 'px' },
        margin: { value: 0, unit: 'auto' },
      },
      children: ['plan1', 'plan2', 'plan3'],
      parentId: 'root',
      events: [],
    },
    'plan1': {
      id: 'plan1',
      type: 'Card',
      name: 'Starter Plan',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        padding: { value: 32, unit: 'px' },
        boxShadow: '0 4px 6px rgba(0,0,0,0.05)',
      },
      children: ['plan1Name', 'plan1Price', 'plan1Desc', 'plan1Btn'],
      parentId: 'grid',
      events: [],
    },
    'plan1Name': {
      id: 'plan1Name',
      type: 'Heading',
      name: 'Plan Name',
      props: { content: 'Starter', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan1Price': {
      id: 'plan1Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$9/mo' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan1Desc': {
      id: 'plan1Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Perfect for individuals and small projects.' },
      styles: {
        color: '#64748b',
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan1Btn': {
      id: 'plan1Btn',
      type: 'Button',
      name: 'CTA',
      props: { label: 'Get Started', variant: 'outline' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 12, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#0f172a',
        border: '2px solid #e5e7eb',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan2': {
      id: 'plan2',
      type: 'Card',
      name: 'Pro Plan',
      props: {},
      styles: {
        backgroundColor: '#0f172a',
        borderRadius: { value: 12, unit: 'px' },
        padding: { value: 32, unit: 'px' },
        boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
        transform: 'scale(1.05)',
      },
      children: ['plan2Badge', 'plan2Name', 'plan2Price', 'plan2Desc', 'plan2Btn'],
      parentId: 'grid',
      events: [],
    },
    'plan2Badge': {
      id: 'plan2Badge',
      type: 'Badge',
      name: 'Popular Badge',
      props: { label: 'Most Popular' },
      styles: {
        backgroundColor: '#3b82f6',
        color: '#ffffff',
        padding: { value: 4, unit: 'px' },
        paddingLeft: { value: 12, unit: 'px' },
        paddingRight: { value: 12, unit: 'px' },
        borderRadius: { value: 16, unit: 'px' },
        fontSize: { value: 12, unit: 'px' },
        fontWeight: 500,
        marginBottom: { value: 16, unit: 'px' },
        display: 'inline-block',
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Name': {
      id: 'plan2Name',
      type: 'Heading',
      name: 'Plan Name',
      props: { content: 'Professional', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#ffffff',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Price': {
      id: 'plan2Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$29/mo' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#ffffff',
        display: 'block',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Desc': {
      id: 'plan2Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'For growing teams that need more power.' },
      styles: {
        color: '#94a3b8',
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Btn': {
      id: 'plan2Btn',
      type: 'Button',
      name: 'CTA',
      props: { label: 'Get Started', variant: 'primary' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 12, unit: 'px' },
        backgroundColor: '#ffffff',
        color: '#0f172a',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan3': {
      id: 'plan3',
      type: 'Card',
      name: 'Enterprise Plan',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        padding: { value: 32, unit: 'px' },
        boxShadow: '0 4px 6px rgba(0,0,0,0.05)',
      },
      children: ['plan3Name', 'plan3Price', 'plan3Desc', 'plan3Btn'],
      parentId: 'grid',
      events: [],
    },
    'plan3Name': {
      id: 'plan3Name',
      type: 'Heading',
      name: 'Plan Name',
      props: { content: 'Enterprise', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
    'plan3Price': {
      id: 'plan3Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$99/mo' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
    'plan3Desc': {
      id: 'plan3Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'For large organizations with custom needs.' },
      styles: {
        color: '#64748b',
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
    'plan3Btn': {
      id: 'plan3Btn',
      type: 'Button',
      name: 'CTA',
      props: { label: 'Contact Sales', variant: 'outline' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 12, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#0f172a',
        border: '2px solid #e5e7eb',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
  },
};

// ============================================================================
// Export All Templates
// ============================================================================

export const additionalBuiltInTemplates: Template[] = [
  dashboardSidebar,
  landingPageSimple,
  navigationHeader,
  pricingTable,
];

export default additionalBuiltInTemplates;
