/**
 * Built-in Templates for the Visual Builder
 *
 * Provides a comprehensive set of pre-designed templates for common layouts.
 */

import type { Template } from './TemplateSystem.js';

// ============================================================================
// Dashboard Templates
// ============================================================================

export const dashboardSidebar: Template = {
  id: 'template_dashboard_sidebar',
  name: 'Dashboard with Sidebar',
  description: 'A dashboard layout with sidebar navigation and content area',
  category: 'dashboard',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['dashboard', 'sidebar', 'admin', 'layout'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Dashboard Layout',
      props: {},
      styles: {
        display: 'flex',
        minHeight: { value: 100, unit: 'vh' },
        backgroundColor: '#f1f5f9',
      },
      children: ['sidebar', 'main'],
      parentId: null,
      events: [],
    },
    'sidebar': {
      id: 'sidebar',
      type: 'Frame',
      name: 'Sidebar',
      props: {},
      styles: {
        width: { value: 250, unit: 'px' },
        backgroundColor: '#1e293b',
        padding: { value: 16, unit: 'px' },
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 8, unit: 'px' },
      },
      children: ['sidebarLogo', 'sidebarNav'],
      parentId: 'root',
      events: [],
    },
    'sidebarLogo': {
      id: 'sidebarLogo',
      type: 'Heading',
      name: 'Logo',
      props: { content: 'Dashboard', level: 'h2' },
      styles: {
        color: '#ffffff',
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 700,
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'sidebar',
      events: [],
    },
    'sidebarNav': {
      id: 'sidebarNav',
      type: 'Stack',
      name: 'Navigation',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 4, unit: 'px' },
      },
      children: ['navHome', 'navAnalytics', 'navSettings'],
      parentId: 'sidebar',
      events: [],
    },
    'navHome': {
      id: 'navHome',
      type: 'NavItem',
      name: 'Home',
      props: { label: 'Home', active: true },
      styles: {
        padding: { value: 12, unit: 'px' },
        borderRadius: { value: 6, unit: 'px' },
        backgroundColor: '#334155',
        color: '#ffffff',
        cursor: 'pointer',
      },
      children: [],
      parentId: 'sidebarNav',
      events: [],
    },
    'navAnalytics': {
      id: 'navAnalytics',
      type: 'NavItem',
      name: 'Analytics',
      props: { label: 'Analytics' },
      styles: {
        padding: { value: 12, unit: 'px' },
        borderRadius: { value: 6, unit: 'px' },
        color: '#94a3b8',
        cursor: 'pointer',
      },
      children: [],
      parentId: 'sidebarNav',
      events: [],
    },
    'navSettings': {
      id: 'navSettings',
      type: 'NavItem',
      name: 'Settings',
      props: { label: 'Settings' },
      styles: {
        padding: { value: 12, unit: 'px' },
        borderRadius: { value: 6, unit: 'px' },
        color: '#94a3b8',
        cursor: 'pointer',
      },
      children: [],
      parentId: 'sidebarNav',
      events: [],
    },
    'main': {
      id: 'main',
      type: 'Frame',
      name: 'Main Content',
      props: {},
      styles: {
        flex: '1',
        padding: { value: 24, unit: 'px' },
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 24, unit: 'px' },
      },
      children: ['header', 'statsGrid', 'content'],
      parentId: 'root',
      events: [],
    },
    'header': {
      id: 'header',
      type: 'HStack',
      name: 'Header',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      children: ['headerTitle', 'headerActions'],
      parentId: 'main',
      events: [],
    },
    'headerTitle': {
      id: 'headerTitle',
      type: 'Heading',
      name: 'Page Title',
      props: { content: 'Dashboard', level: 'h1' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'headerActions': {
      id: 'headerActions',
      type: 'HStack',
      name: 'Actions',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 8, unit: 'px' },
      },
      children: ['actionBtn'],
      parentId: 'header',
      events: [],
    },
    'actionBtn': {
      id: 'actionBtn',
      type: 'Button',
      name: 'Add New',
      props: { label: '+ Add New', variant: 'primary' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 20, unit: 'px' },
        paddingRight: { value: 20, unit: 'px' },
        backgroundColor: '#2563eb',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'headerActions',
      events: [],
    },
    'statsGrid': {
      id: 'statsGrid',
      type: 'Grid',
      name: 'Stats Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: { value: 16, unit: 'px' },
      },
      children: ['stat1', 'stat2', 'stat3', 'stat4'],
      parentId: 'main',
      events: [],
    },
    'stat1': {
      id: 'stat1',
      type: 'Card',
      name: 'Stat Card 1',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat1Label', 'stat1Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat1Label': {
      id: 'stat1Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Total Users' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat1',
      events: [],
    },
    'stat1Value': {
      id: 'stat1Value',
      type: 'Text',
      name: 'Value',
      props: { content: '12,543' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat1',
      events: [],
    },
    'stat2': {
      id: 'stat2',
      type: 'Card',
      name: 'Stat Card 2',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat2Label', 'stat2Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat2Label': {
      id: 'stat2Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Revenue' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat2',
      events: [],
    },
    'stat2Value': {
      id: 'stat2Value',
      type: 'Text',
      name: 'Value',
      props: { content: '$45,234' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat2',
      events: [],
    },
    'stat3': {
      id: 'stat3',
      type: 'Card',
      name: 'Stat Card 3',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat3Label', 'stat3Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat3Label': {
      id: 'stat3Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Orders' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat3',
      events: [],
    },
    'stat3Value': {
      id: 'stat3Value',
      type: 'Text',
      name: 'Value',
      props: { content: '1,234' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat3',
      events: [],
    },
    'stat4': {
      id: 'stat4',
      type: 'Card',
      name: 'Stat Card 4',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        padding: { value: 20, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['stat4Label', 'stat4Value'],
      parentId: 'statsGrid',
      events: [],
    },
    'stat4Label': {
      id: 'stat4Label',
      type: 'Text',
      name: 'Label',
      props: { content: 'Conversion' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'stat4',
      events: [],
    },
    'stat4Value': {
      id: 'stat4Value',
      type: 'Text',
      name: 'Value',
      props: { content: '3.24%' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 'stat4',
      events: [],
    },
    'content': {
      id: 'content',
      type: 'Card',
      name: 'Content Area',
      props: {},
      styles: {
        flex: '1',
        backgroundColor: '#ffffff',
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['contentTitle', 'contentPlaceholder'],
      parentId: 'main',
      events: [],
    },
    'contentTitle': {
      id: 'contentTitle',
      type: 'Heading',
      name: 'Section Title',
      props: { content: 'Recent Activity', level: 'h3' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'content',
      events: [],
    },
    'contentPlaceholder': {
      id: 'contentPlaceholder',
      type: 'Paragraph',
      name: 'Placeholder',
      props: { content: 'Add your content here. This could be a table, chart, or list.' },
      styles: {
        color: '#64748b',
      },
      children: [],
      parentId: 'content',
      events: [],
    },
  },
};

// ============================================================================
// Landing Page Templates
// ============================================================================

export const landingPageSimple: Template = {
  id: 'template_landing_simple',
  name: 'Simple Landing Page',
  description: 'A clean landing page with hero, features, and footer',
  category: 'landing',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['landing', 'marketing', 'hero', 'features'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Landing Page',
      props: {},
      styles: {
        minHeight: { value: 100, unit: 'vh' },
        backgroundColor: '#ffffff',
      },
      children: ['navbar', 'hero', 'features', 'footer'],
      parentId: null,
      events: [],
    },
    'navbar': {
      id: 'navbar',
      type: 'Nav',
      name: 'Navigation Bar',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 64, unit: 'px' },
        paddingRight: { value: 64, unit: 'px' },
        borderBottom: '1px solid #e5e7eb',
      },
      children: ['navLogo', 'navLinks', 'navCta'],
      parentId: 'root',
      events: [],
    },
    'navLogo': {
      id: 'navLogo',
      type: 'Heading',
      name: 'Logo',
      props: { content: 'Brand', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'navbar',
      events: [],
    },
    'navLinks': {
      id: 'navLinks',
      type: 'HStack',
      name: 'Nav Links',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 32, unit: 'px' },
      },
      children: ['navLink1', 'navLink2', 'navLink3'],
      parentId: 'navbar',
      events: [],
    },
    'navLink1': {
      id: 'navLink1',
      type: 'Link',
      name: 'Features',
      props: { label: 'Features', href: '#features' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'navLinks',
      events: [],
    },
    'navLink2': {
      id: 'navLink2',
      type: 'Link',
      name: 'Pricing',
      props: { label: 'Pricing', href: '#pricing' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'navLinks',
      events: [],
    },
    'navLink3': {
      id: 'navLink3',
      type: 'Link',
      name: 'About',
      props: { label: 'About', href: '#about' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'navLinks',
      events: [],
    },
    'navCta': {
      id: 'navCta',
      type: 'Button',
      name: 'Get Started',
      props: { label: 'Get Started', variant: 'primary' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 20, unit: 'px' },
        paddingRight: { value: 20, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'navbar',
      events: [],
    },
    'hero': {
      id: 'hero',
      type: 'Frame',
      name: 'Hero Section',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: { value: 80, unit: 'px' },
        paddingTop: { value: 120, unit: 'px' },
        paddingBottom: { value: 120, unit: 'px' },
        backgroundColor: '#f8fafc',
      },
      children: ['heroTitle', 'heroSubtitle', 'heroButtons'],
      parentId: 'root',
      events: [],
    },
    'heroTitle': {
      id: 'heroTitle',
      type: 'Heading',
      name: 'Hero Title',
      props: { content: 'Build Something Amazing', level: 'h1' },
      styles: {
        fontSize: { value: 56, unit: 'px' },
        fontWeight: 800,
        color: '#0f172a',
        marginBottom: { value: 24, unit: 'px' },
        lineHeight: { value: 1.1, unit: 'none' },
      },
      children: [],
      parentId: 'hero',
      events: [],
    },
    'heroSubtitle': {
      id: 'heroSubtitle',
      type: 'Paragraph',
      name: 'Hero Subtitle',
      props: { content: 'The fastest way to build production-ready applications. Start building in minutes with our intuitive tools and components.' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        color: '#64748b',
        maxWidth: { value: 600, unit: 'px' },
        marginBottom: { value: 40, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'hero',
      events: [],
    },
    'heroButtons': {
      id: 'heroButtons',
      type: 'HStack',
      name: 'Hero Buttons',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 16, unit: 'px' },
      },
      children: ['heroPrimaryBtn', 'heroSecondaryBtn'],
      parentId: 'hero',
      events: [],
    },
    'heroPrimaryBtn': {
      id: 'heroPrimaryBtn',
      type: 'Button',
      name: 'Primary CTA',
      props: { label: 'Start Free Trial', variant: 'primary' },
      styles: {
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 32, unit: 'px' },
        paddingRight: { value: 32, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        fontWeight: 600,
        fontSize: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'heroButtons',
      events: [],
    },
    'heroSecondaryBtn': {
      id: 'heroSecondaryBtn',
      type: 'Button',
      name: 'Secondary CTA',
      props: { label: 'Watch Demo', variant: 'outline' },
      styles: {
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 32, unit: 'px' },
        paddingRight: { value: 32, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#0f172a',
        border: '2px solid #0f172a',
        borderRadius: { value: 8, unit: 'px' },
        fontWeight: 600,
        fontSize: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'heroButtons',
      events: [],
    },
    'features': {
      id: 'features',
      type: 'Frame',
      name: 'Features Section',
      props: {},
      styles: {
        padding: { value: 80, unit: 'px' },
        paddingLeft: { value: 64, unit: 'px' },
        paddingRight: { value: 64, unit: 'px' },
      },
      children: ['featuresTitle', 'featuresGrid'],
      parentId: 'root',
      events: [],
    },
    'featuresTitle': {
      id: 'featuresTitle',
      type: 'Heading',
      name: 'Features Title',
      props: { content: 'Everything you need', level: 'h2' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        textAlign: 'center',
        marginBottom: { value: 48, unit: 'px' },
      },
      children: [],
      parentId: 'features',
      events: [],
    },
    'featuresGrid': {
      id: 'featuresGrid',
      type: 'Grid',
      name: 'Features Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: { value: 32, unit: 'px' },
      },
      children: ['feature1', 'feature2', 'feature3'],
      parentId: 'features',
      events: [],
    },
    'feature1': {
      id: 'feature1',
      type: 'Card',
      name: 'Feature 1',
      props: {},
      styles: {
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 12, unit: 'px' },
        border: '1px solid #e5e7eb',
      },
      children: ['feature1Title', 'feature1Desc'],
      parentId: 'featuresGrid',
      events: [],
    },
    'feature1Title': {
      id: 'feature1Title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Fast Performance', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: [],
      parentId: 'feature1',
      events: [],
    },
    'feature1Desc': {
      id: 'feature1Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Optimized for speed with minimal bundle size and efficient rendering.' },
      styles: {
        color: '#64748b',
        fontSize: { value: 15, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'feature1',
      events: [],
    },
    'feature2': {
      id: 'feature2',
      type: 'Card',
      name: 'Feature 2',
      props: {},
      styles: {
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 12, unit: 'px' },
        border: '1px solid #e5e7eb',
      },
      children: ['feature2Title', 'feature2Desc'],
      parentId: 'featuresGrid',
      events: [],
    },
    'feature2Title': {
      id: 'feature2Title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Easy to Use', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: [],
      parentId: 'feature2',
      events: [],
    },
    'feature2Desc': {
      id: 'feature2Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Intuitive API design that gets you started in minutes, not hours.' },
      styles: {
        color: '#64748b',
        fontSize: { value: 15, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'feature2',
      events: [],
    },
    'feature3': {
      id: 'feature3',
      type: 'Card',
      name: 'Feature 3',
      props: {},
      styles: {
        padding: { value: 24, unit: 'px' },
        borderRadius: { value: 12, unit: 'px' },
        border: '1px solid #e5e7eb',
      },
      children: ['feature3Title', 'feature3Desc'],
      parentId: 'featuresGrid',
      events: [],
    },
    'feature3Title': {
      id: 'feature3Title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Fully Customizable', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: [],
      parentId: 'feature3',
      events: [],
    },
    'feature3Desc': {
      id: 'feature3Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Extend and customize everything to match your brand and requirements.' },
      styles: {
        color: '#64748b',
        fontSize: { value: 15, unit: 'px' },
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'feature3',
      events: [],
    },
    'footer': {
      id: 'footer',
      type: 'Frame',
      name: 'Footer',
      props: {},
      styles: {
        padding: { value: 48, unit: 'px' },
        paddingLeft: { value: 64, unit: 'px' },
        paddingRight: { value: 64, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#94a3b8',
        textAlign: 'center',
      },
      children: ['footerText'],
      parentId: 'root',
      events: [],
    },
    'footerText': {
      id: 'footerText',
      type: 'Paragraph',
      name: 'Copyright',
      props: { content: '2025 Your Company. All rights reserved.' },
      styles: {
        color: '#94a3b8',
        fontSize: { value: 14, unit: 'px' },
      },
      children: [],
      parentId: 'footer',
      events: [],
    },
  },
};

// ============================================================================
// Navigation Templates
// ============================================================================

export const navigationHeader: Template = {
  id: 'template_nav_header',
  name: 'Header Navigation',
  description: 'A responsive header with logo, navigation links, and actions',
  category: 'navigation',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['header', 'navigation', 'navbar', 'responsive'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Nav',
      name: 'Header Navigation',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 16, unit: 'px' },
        paddingLeft: { value: 24, unit: 'px' },
        paddingRight: { value: 24, unit: 'px' },
        backgroundColor: '#ffffff',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
        position: 'sticky',
        top: { value: 0, unit: 'px' },
        zIndex: 100,
      },
      children: ['logo', 'links', 'actions'],
      parentId: null,
      events: [],
    },
    'logo': {
      id: 'logo',
      type: 'HStack',
      name: 'Logo Area',
      props: {},
      styles: {
        display: 'flex',
        alignItems: 'center',
        gap: { value: 8, unit: 'px' },
      },
      children: ['logoText'],
      parentId: 'root',
      events: [],
    },
    'logoText': {
      id: 'logoText',
      type: 'Heading',
      name: 'Logo',
      props: { content: 'Logo', level: 'h3' },
      styles: {
        fontSize: { value: 24, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'logo',
      events: [],
    },
    'links': {
      id: 'links',
      type: 'HStack',
      name: 'Navigation Links',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 32, unit: 'px' },
      },
      children: ['link1', 'link2', 'link3', 'link4'],
      parentId: 'root',
      events: [],
    },
    'link1': {
      id: 'link1',
      type: 'Link',
      name: 'Home',
      props: { label: 'Home', href: '/' },
      styles: {
        color: '#0f172a',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'link2': {
      id: 'link2',
      type: 'Link',
      name: 'Products',
      props: { label: 'Products', href: '/products' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'link3': {
      id: 'link3',
      type: 'Link',
      name: 'Pricing',
      props: { label: 'Pricing', href: '/pricing' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'link4': {
      id: 'link4',
      type: 'Link',
      name: 'Contact',
      props: { label: 'Contact', href: '/contact' },
      styles: {
        color: '#64748b',
        fontWeight: 500,
        textDecoration: 'none',
      },
      children: [],
      parentId: 'links',
      events: [],
    },
    'actions': {
      id: 'actions',
      type: 'HStack',
      name: 'Actions',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 12, unit: 'px' },
      },
      children: ['loginBtn', 'signupBtn'],
      parentId: 'root',
      events: [],
    },
    'loginBtn': {
      id: 'loginBtn',
      type: 'Button',
      name: 'Login',
      props: { label: 'Log In', variant: 'ghost' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 16, unit: 'px' },
        paddingRight: { value: 16, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#64748b',
        fontWeight: 500,
      },
      children: [],
      parentId: 'actions',
      events: [],
    },
    'signupBtn': {
      id: 'signupBtn',
      type: 'Button',
      name: 'Sign Up',
      props: { label: 'Sign Up', variant: 'primary' },
      styles: {
        padding: { value: 10, unit: 'px' },
        paddingLeft: { value: 20, unit: 'px' },
        paddingRight: { value: 20, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'actions',
      events: [],
    },
  },
};

// ============================================================================
// Content Templates
// ============================================================================

export const pricingTable: Template = {
  id: 'template_pricing_table',
  name: 'Pricing Table',
  description: 'A three-tier pricing table with features comparison',
  category: 'content',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['pricing', 'table', 'plans', 'comparison'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Pricing Section',
      props: {},
      styles: {
        padding: { value: 64, unit: 'px' },
        backgroundColor: '#f8fafc',
      },
      children: ['title', 'subtitle', 'grid'],
      parentId: null,
      events: [],
    },
    'title': {
      id: 'title',
      type: 'Heading',
      name: 'Section Title',
      props: { content: 'Simple, transparent pricing', level: 'h2' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        textAlign: 'center',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'root',
      events: [],
    },
    'subtitle': {
      id: 'subtitle',
      type: 'Paragraph',
      name: 'Subtitle',
      props: { content: 'Choose the plan that works best for you and your team.' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        color: '#64748b',
        textAlign: 'center',
        marginBottom: { value: 48, unit: 'px' },
      },
      children: [],
      parentId: 'root',
      events: [],
    },
    'grid': {
      id: 'grid',
      type: 'Grid',
      name: 'Pricing Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: { value: 24, unit: 'px' },
        maxWidth: { value: 1000, unit: 'px' },
        margin: { value: 0, unit: 'auto' },
      },
      children: ['plan1', 'plan2', 'plan3'],
      parentId: 'root',
      events: [],
    },
    'plan1': {
      id: 'plan1',
      type: 'Card',
      name: 'Starter Plan',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        padding: { value: 32, unit: 'px' },
        boxShadow: '0 4px 6px rgba(0,0,0,0.05)',
      },
      children: ['plan1Name', 'plan1Price', 'plan1Desc', 'plan1Btn'],
      parentId: 'grid',
      events: [],
    },
    'plan1Name': {
      id: 'plan1Name',
      type: 'Heading',
      name: 'Plan Name',
      props: { content: 'Starter', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan1Price': {
      id: 'plan1Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$9/mo' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan1Desc': {
      id: 'plan1Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'Perfect for individuals and small projects.' },
      styles: {
        color: '#64748b',
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan1Btn': {
      id: 'plan1Btn',
      type: 'Button',
      name: 'CTA',
      props: { label: 'Get Started', variant: 'outline' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 12, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#0f172a',
        border: '2px solid #e5e7eb',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'plan1',
      events: [],
    },
    'plan2': {
      id: 'plan2',
      type: 'Card',
      name: 'Pro Plan',
      props: {},
      styles: {
        backgroundColor: '#0f172a',
        borderRadius: { value: 12, unit: 'px' },
        padding: { value: 32, unit: 'px' },
        boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
        transform: 'scale(1.05)',
      },
      children: ['plan2Badge', 'plan2Name', 'plan2Price', 'plan2Desc', 'plan2Btn'],
      parentId: 'grid',
      events: [],
    },
    'plan2Badge': {
      id: 'plan2Badge',
      type: 'Badge',
      name: 'Popular Badge',
      props: { label: 'Most Popular' },
      styles: {
        backgroundColor: '#3b82f6',
        color: '#ffffff',
        padding: { value: 4, unit: 'px' },
        paddingLeft: { value: 12, unit: 'px' },
        paddingRight: { value: 12, unit: 'px' },
        borderRadius: { value: 16, unit: 'px' },
        fontSize: { value: 12, unit: 'px' },
        fontWeight: 500,
        marginBottom: { value: 16, unit: 'px' },
        display: 'inline-block',
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Name': {
      id: 'plan2Name',
      type: 'Heading',
      name: 'Plan Name',
      props: { content: 'Professional', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#ffffff',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Price': {
      id: 'plan2Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$29/mo' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#ffffff',
        display: 'block',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Desc': {
      id: 'plan2Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'For growing teams that need more power.' },
      styles: {
        color: '#94a3b8',
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan2Btn': {
      id: 'plan2Btn',
      type: 'Button',
      name: 'CTA',
      props: { label: 'Get Started', variant: 'primary' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 12, unit: 'px' },
        backgroundColor: '#ffffff',
        color: '#0f172a',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'plan2',
      events: [],
    },
    'plan3': {
      id: 'plan3',
      type: 'Card',
      name: 'Enterprise Plan',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        padding: { value: 32, unit: 'px' },
        boxShadow: '0 4px 6px rgba(0,0,0,0.05)',
      },
      children: ['plan3Name', 'plan3Price', 'plan3Desc', 'plan3Btn'],
      parentId: 'grid',
      events: [],
    },
    'plan3Name': {
      id: 'plan3Name',
      type: 'Heading',
      name: 'Plan Name',
      props: { content: 'Enterprise', level: 'h3' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
    'plan3Price': {
      id: 'plan3Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$99/mo' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        display: 'block',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
    'plan3Desc': {
      id: 'plan3Desc',
      type: 'Paragraph',
      name: 'Description',
      props: { content: 'For large organizations with custom needs.' },
      styles: {
        color: '#64748b',
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
    'plan3Btn': {
      id: 'plan3Btn',
      type: 'Button',
      name: 'CTA',
      props: { label: 'Contact Sales', variant: 'outline' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 12, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#0f172a',
        border: '2px solid #e5e7eb',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'plan3',
      events: [],
    },
  },
};

// ============================================================================
// Authentication Templates
// ============================================================================

export const loginForm: Template = {
  id: 'template_login_form',
  name: 'Login Form',
  description: 'A clean login form with email and password fields',
  category: 'form',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['login', 'form', 'authentication', 'auth'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Login Container',
      props: {},
      styles: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: { value: 100, unit: 'vh' },
        backgroundColor: '#f1f5f9',
        padding: { value: 24, unit: 'px' },
      },
      children: ['card'],
      parentId: null,
      events: [],
    },
    'card': {
      id: 'card',
      type: 'Card',
      name: 'Login Card',
      props: {},
      styles: {
        width: { value: 400, unit: 'px' },
        maxWidth: { value: 100, unit: '%' },
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        padding: { value: 40, unit: 'px' },
        boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
      },
      children: ['logo', 'title', 'subtitle', 'form', 'divider', 'socialButtons', 'signup'],
      parentId: 'root',
      events: [],
    },
    'logo': {
      id: 'logo',
      type: 'Frame',
      name: 'Logo Container',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'center',
        marginBottom: { value: 24, unit: 'px' },
      },
      children: ['logoText'],
      parentId: 'card',
      events: [],
    },
    'logoText': {
      id: 'logoText',
      type: 'Heading',
      name: 'Logo',
      props: { content: 'Brand', level: 'h2' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'logo',
      events: [],
    },
    'title': {
      id: 'title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Welcome back', level: 'h1' },
      styles: {
        fontSize: { value: 24, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        textAlign: 'center',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'card',
      events: [],
    },
    'subtitle': {
      id: 'subtitle',
      type: 'Paragraph',
      name: 'Subtitle',
      props: { content: 'Sign in to your account to continue' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        textAlign: 'center',
        marginBottom: { value: 32, unit: 'px' },
      },
      children: [],
      parentId: 'card',
      events: [],
    },
    'form': {
      id: 'form',
      type: 'Form',
      name: 'Login Form',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 16, unit: 'px' },
      },
      children: ['emailField', 'passwordField', 'rememberRow', 'submitBtn'],
      parentId: 'card',
      events: [],
    },
    'emailField': {
      id: 'emailField',
      type: 'Input',
      name: 'Email',
      props: { label: 'Email address', type: 'email', placeholder: 'you@example.com' },
      styles: {
        width: { value: 100, unit: '%' },
      },
      children: [],
      parentId: 'form',
      events: [],
    },
    'passwordField': {
      id: 'passwordField',
      type: 'Input',
      name: 'Password',
      props: { label: 'Password', type: 'password', placeholder: 'Enter your password' },
      styles: {
        width: { value: 100, unit: '%' },
      },
      children: [],
      parentId: 'form',
      events: [],
    },
    'rememberRow': {
      id: 'rememberRow',
      type: 'HStack',
      name: 'Remember Row',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      children: ['rememberCheck', 'forgotLink'],
      parentId: 'form',
      events: [],
    },
    'rememberCheck': {
      id: 'rememberCheck',
      type: 'Checkbox',
      name: 'Remember Me',
      props: { label: 'Remember me' },
      styles: {},
      children: [],
      parentId: 'rememberRow',
      events: [],
    },
    'forgotLink': {
      id: 'forgotLink',
      type: 'Link',
      name: 'Forgot Password',
      props: { label: 'Forgot password?', href: '/forgot-password' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#3b82f6',
        textDecoration: 'none',
      },
      children: [],
      parentId: 'rememberRow',
      events: [],
    },
    'submitBtn': {
      id: 'submitBtn',
      type: 'Button',
      name: 'Sign In',
      props: { label: 'Sign in', variant: 'primary', type: 'submit' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 12, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        fontWeight: 600,
        marginTop: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'form',
      events: [],
    },
    'divider': {
      id: 'divider',
      type: 'HStack',
      name: 'Divider',
      props: {},
      styles: {
        display: 'flex',
        alignItems: 'center',
        gap: { value: 16, unit: 'px' },
        marginTop: { value: 24, unit: 'px' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: ['dividerLine1', 'dividerText', 'dividerLine2'],
      parentId: 'card',
      events: [],
    },
    'dividerLine1': {
      id: 'dividerLine1',
      type: 'Frame',
      name: 'Line',
      props: {},
      styles: {
        flex: '1',
        height: { value: 1, unit: 'px' },
        backgroundColor: '#e5e7eb',
      },
      children: [],
      parentId: 'divider',
      events: [],
    },
    'dividerText': {
      id: 'dividerText',
      type: 'Text',
      name: 'Or',
      props: { content: 'or continue with' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#94a3b8',
      },
      children: [],
      parentId: 'divider',
      events: [],
    },
    'dividerLine2': {
      id: 'dividerLine2',
      type: 'Frame',
      name: 'Line',
      props: {},
      styles: {
        flex: '1',
        height: { value: 1, unit: 'px' },
        backgroundColor: '#e5e7eb',
      },
      children: [],
      parentId: 'divider',
      events: [],
    },
    'socialButtons': {
      id: 'socialButtons',
      type: 'Grid',
      name: 'Social Buttons',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: { value: 12, unit: 'px' },
      },
      children: ['googleBtn', 'githubBtn'],
      parentId: 'card',
      events: [],
    },
    'googleBtn': {
      id: 'googleBtn',
      type: 'Button',
      name: 'Google',
      props: { label: 'Google', variant: 'outline' },
      styles: {
        padding: { value: 10, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#374151',
        border: '1px solid #e5e7eb',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'socialButtons',
      events: [],
    },
    'githubBtn': {
      id: 'githubBtn',
      type: 'Button',
      name: 'GitHub',
      props: { label: 'GitHub', variant: 'outline' },
      styles: {
        padding: { value: 10, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#374151',
        border: '1px solid #e5e7eb',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'socialButtons',
      events: [],
    },
    'signup': {
      id: 'signup',
      type: 'Paragraph',
      name: 'Sign Up Link',
      props: { content: "Don't have an account? Sign up" },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        textAlign: 'center',
        marginTop: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'card',
      events: [],
    },
  },
};

// ============================================================================
// Blog Templates
// ============================================================================

export const blogArticle: Template = {
  id: 'template_blog_article',
  name: 'Blog Article',
  description: 'A blog article layout with header, content, and sidebar',
  category: 'content',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['blog', 'article', 'content', 'reading'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Article Page',
      props: {},
      styles: {
        maxWidth: { value: 1200, unit: 'px' },
        margin: { value: 0, unit: 'auto' },
        padding: { value: 32, unit: 'px' },
      },
      children: ['articleHeader', 'articleBody'],
      parentId: null,
      events: [],
    },
    'articleHeader': {
      id: 'articleHeader',
      type: 'Frame',
      name: 'Article Header',
      props: {},
      styles: {
        marginBottom: { value: 48, unit: 'px' },
        textAlign: 'center',
      },
      children: ['category', 'title', 'meta', 'featuredImage'],
      parentId: 'root',
      events: [],
    },
    'category': {
      id: 'category',
      type: 'Badge',
      name: 'Category',
      props: { label: 'Technology' },
      styles: {
        backgroundColor: '#e0f2fe',
        color: '#0369a1',
        padding: { value: 6, unit: 'px' },
        paddingLeft: { value: 12, unit: 'px' },
        paddingRight: { value: 12, unit: 'px' },
        borderRadius: { value: 16, unit: 'px' },
        fontSize: { value: 12, unit: 'px' },
        fontWeight: 600,
        marginBottom: { value: 16, unit: 'px' },
        display: 'inline-block',
      },
      children: [],
      parentId: 'articleHeader',
      events: [],
    },
    'title': {
      id: 'title',
      type: 'Heading',
      name: 'Article Title',
      props: { content: 'Building Modern Web Applications with PhilJS', level: 'h1' },
      styles: {
        fontSize: { value: 42, unit: 'px' },
        fontWeight: 800,
        color: '#0f172a',
        lineHeight: { value: 1.2, unit: 'none' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'articleHeader',
      events: [],
    },
    'meta': {
      id: 'meta',
      type: 'HStack',
      name: 'Article Meta',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: { value: 16, unit: 'px' },
        marginBottom: { value: 32, unit: 'px' },
      },
      children: ['authorAvatar', 'authorName', 'metaDot', 'publishDate', 'metaDot2', 'readTime'],
      parentId: 'articleHeader',
      events: [],
    },
    'authorAvatar': {
      id: 'authorAvatar',
      type: 'Frame',
      name: 'Avatar',
      props: {},
      styles: {
        width: { value: 40, unit: 'px' },
        height: { value: 40, unit: 'px' },
        borderRadius: { value: 20, unit: 'px' },
        backgroundColor: '#e2e8f0',
      },
      children: [],
      parentId: 'meta',
      events: [],
    },
    'authorName': {
      id: 'authorName',
      type: 'Text',
      name: 'Author',
      props: { content: 'John Doe' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        fontWeight: 500,
        color: '#0f172a',
      },
      children: [],
      parentId: 'meta',
      events: [],
    },
    'metaDot': {
      id: 'metaDot',
      type: 'Text',
      name: 'Dot',
      props: { content: '·' },
      styles: {
        color: '#94a3b8',
      },
      children: [],
      parentId: 'meta',
      events: [],
    },
    'publishDate': {
      id: 'publishDate',
      type: 'Text',
      name: 'Date',
      props: { content: 'Dec 20, 2025' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'meta',
      events: [],
    },
    'metaDot2': {
      id: 'metaDot2',
      type: 'Text',
      name: 'Dot',
      props: { content: '·' },
      styles: {
        color: '#94a3b8',
      },
      children: [],
      parentId: 'meta',
      events: [],
    },
    'readTime': {
      id: 'readTime',
      type: 'Text',
      name: 'Read Time',
      props: { content: '5 min read' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'meta',
      events: [],
    },
    'featuredImage': {
      id: 'featuredImage',
      type: 'Frame',
      name: 'Featured Image',
      props: {},
      styles: {
        width: { value: 100, unit: '%' },
        height: { value: 400, unit: 'px' },
        backgroundColor: '#e2e8f0',
        borderRadius: { value: 12, unit: 'px' },
      },
      children: [],
      parentId: 'articleHeader',
      events: [],
    },
    'articleBody': {
      id: 'articleBody',
      type: 'HStack',
      name: 'Article Body',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 48, unit: 'px' },
      },
      children: ['content', 'sidebar'],
      parentId: 'root',
      events: [],
    },
    'content': {
      id: 'content',
      type: 'Frame',
      name: 'Content',
      props: {},
      styles: {
        flex: '1',
        maxWidth: { value: 700, unit: 'px' },
      },
      children: ['intro', 'paragraph1', 'subheading', 'paragraph2'],
      parentId: 'articleBody',
      events: [],
    },
    'intro': {
      id: 'intro',
      type: 'Paragraph',
      name: 'Introduction',
      props: { content: 'In this comprehensive guide, we will explore the fundamentals of building modern web applications using PhilJS. From reactive state management to component composition, we cover everything you need to know.' },
      styles: {
        fontSize: { value: 20, unit: 'px' },
        color: '#374151',
        lineHeight: { value: 1.8, unit: 'none' },
        marginBottom: { value: 32, unit: 'px' },
      },
      children: [],
      parentId: 'content',
      events: [],
    },
    'paragraph1': {
      id: 'paragraph1',
      type: 'Paragraph',
      name: 'Paragraph 1',
      props: { content: 'PhilJS is a modern JavaScript framework designed for building fast, reactive user interfaces. It leverages fine-grained reactivity to ensure optimal performance, updating only the parts of the DOM that actually change.' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        color: '#4b5563',
        lineHeight: { value: 1.8, unit: 'none' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'content',
      events: [],
    },
    'subheading': {
      id: 'subheading',
      type: 'Heading',
      name: 'Subheading',
      props: { content: 'Getting Started', level: 'h2' },
      styles: {
        fontSize: { value: 28, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        marginTop: { value: 32, unit: 'px' },
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'content',
      events: [],
    },
    'paragraph2': {
      id: 'paragraph2',
      type: 'Paragraph',
      name: 'Paragraph 2',
      props: { content: 'To begin using PhilJS, you can install it via npm or yarn. The framework provides a simple yet powerful API for creating reactive components that efficiently update when their state changes.' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        color: '#4b5563',
        lineHeight: { value: 1.8, unit: 'none' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'content',
      events: [],
    },
    'sidebar': {
      id: 'sidebar',
      type: 'Frame',
      name: 'Sidebar',
      props: {},
      styles: {
        width: { value: 300, unit: 'px' },
        flexShrink: 0,
      },
      children: ['tocCard', 'relatedCard'],
      parentId: 'articleBody',
      events: [],
    },
    'tocCard': {
      id: 'tocCard',
      type: 'Card',
      name: 'Table of Contents',
      props: {},
      styles: {
        backgroundColor: '#f8fafc',
        borderRadius: { value: 8, unit: 'px' },
        padding: { value: 24, unit: 'px' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: ['tocTitle', 'tocItems'],
      parentId: 'sidebar',
      events: [],
    },
    'tocTitle': {
      id: 'tocTitle',
      type: 'Heading',
      name: 'TOC Title',
      props: { content: 'Table of Contents', level: 'h4' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
        textTransform: 'uppercase',
        letterSpacing: { value: 0.5, unit: 'px' },
      },
      children: [],
      parentId: 'tocCard',
      events: [],
    },
    'tocItems': {
      id: 'tocItems',
      type: 'Stack',
      name: 'TOC Items',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 8, unit: 'px' },
      },
      children: ['tocItem1', 'tocItem2', 'tocItem3'],
      parentId: 'tocCard',
      events: [],
    },
    'tocItem1': {
      id: 'tocItem1',
      type: 'Link',
      name: 'TOC Link',
      props: { label: 'Introduction', href: '#intro' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        textDecoration: 'none',
      },
      children: [],
      parentId: 'tocItems',
      events: [],
    },
    'tocItem2': {
      id: 'tocItem2',
      type: 'Link',
      name: 'TOC Link',
      props: { label: 'Getting Started', href: '#getting-started' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        textDecoration: 'none',
      },
      children: [],
      parentId: 'tocItems',
      events: [],
    },
    'tocItem3': {
      id: 'tocItem3',
      type: 'Link',
      name: 'TOC Link',
      props: { label: 'Conclusion', href: '#conclusion' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        textDecoration: 'none',
      },
      children: [],
      parentId: 'tocItems',
      events: [],
    },
    'relatedCard': {
      id: 'relatedCard',
      type: 'Card',
      name: 'Related Articles',
      props: {},
      styles: {
        backgroundColor: '#f8fafc',
        borderRadius: { value: 8, unit: 'px' },
        padding: { value: 24, unit: 'px' },
      },
      children: ['relatedTitle', 'relatedItems'],
      parentId: 'sidebar',
      events: [],
    },
    'relatedTitle': {
      id: 'relatedTitle',
      type: 'Heading',
      name: 'Related Title',
      props: { content: 'Related Articles', level: 'h4' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
        textTransform: 'uppercase',
        letterSpacing: { value: 0.5, unit: 'px' },
      },
      children: [],
      parentId: 'relatedCard',
      events: [],
    },
    'relatedItems': {
      id: 'relatedItems',
      type: 'Stack',
      name: 'Related Items',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: { value: 12, unit: 'px' },
      },
      children: ['relatedItem1', 'relatedItem2'],
      parentId: 'relatedCard',
      events: [],
    },
    'relatedItem1': {
      id: 'relatedItem1',
      type: 'Link',
      name: 'Related Link',
      props: { label: 'Understanding Reactivity in PhilJS', href: '/articles/reactivity' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#3b82f6',
        textDecoration: 'none',
      },
      children: [],
      parentId: 'relatedItems',
      events: [],
    },
    'relatedItem2': {
      id: 'relatedItem2',
      type: 'Link',
      name: 'Related Link',
      props: { label: 'Component Patterns', href: '/articles/patterns' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#3b82f6',
        textDecoration: 'none',
      },
      children: [],
      parentId: 'relatedItems',
      events: [],
    },
  },
};

// ============================================================================
// E-commerce Templates
// ============================================================================

export const productGrid: Template = {
  id: 'template_product_grid',
  name: 'Product Grid',
  description: 'An e-commerce product grid with filters and cards',
  category: 'ecommerce',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['ecommerce', 'products', 'grid', 'shop'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Product Page',
      props: {},
      styles: {
        padding: { value: 32, unit: 'px' },
        backgroundColor: '#f8fafc',
        minHeight: { value: 100, unit: 'vh' },
      },
      children: ['header', 'filterBar', 'productsGrid'],
      parentId: null,
      events: [],
    },
    'header': {
      id: 'header',
      type: 'Frame',
      name: 'Header',
      props: {},
      styles: {
        marginBottom: { value: 32, unit: 'px' },
      },
      children: ['title', 'subtitle'],
      parentId: 'root',
      events: [],
    },
    'title': {
      id: 'title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Our Products', level: 'h1' },
      styles: {
        fontSize: { value: 32, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'subtitle': {
      id: 'subtitle',
      type: 'Paragraph',
      name: 'Subtitle',
      props: { content: 'Discover our collection of premium products' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'filterBar': {
      id: 'filterBar',
      type: 'HStack',
      name: 'Filter Bar',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: { value: 24, unit: 'px' },
        padding: { value: 16, unit: 'px' },
        backgroundColor: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      },
      children: ['categories', 'sortSelect'],
      parentId: 'root',
      events: [],
    },
    'categories': {
      id: 'categories',
      type: 'HStack',
      name: 'Categories',
      props: {},
      styles: {
        display: 'flex',
        gap: { value: 8, unit: 'px' },
      },
      children: ['catAll', 'catElectronics', 'catClothing', 'catHome'],
      parentId: 'filterBar',
      events: [],
    },
    'catAll': {
      id: 'catAll',
      type: 'Button',
      name: 'All',
      props: { label: 'All', variant: 'primary' },
      styles: {
        padding: { value: 8, unit: 'px' },
        paddingLeft: { value: 16, unit: 'px' },
        paddingRight: { value: 16, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 20, unit: 'px' },
        fontSize: { value: 14, unit: 'px' },
      },
      children: [],
      parentId: 'categories',
      events: [],
    },
    'catElectronics': {
      id: 'catElectronics',
      type: 'Button',
      name: 'Electronics',
      props: { label: 'Electronics', variant: 'ghost' },
      styles: {
        padding: { value: 8, unit: 'px' },
        paddingLeft: { value: 16, unit: 'px' },
        paddingRight: { value: 16, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#64748b',
        borderRadius: { value: 20, unit: 'px' },
        fontSize: { value: 14, unit: 'px' },
      },
      children: [],
      parentId: 'categories',
      events: [],
    },
    'catClothing': {
      id: 'catClothing',
      type: 'Button',
      name: 'Clothing',
      props: { label: 'Clothing', variant: 'ghost' },
      styles: {
        padding: { value: 8, unit: 'px' },
        paddingLeft: { value: 16, unit: 'px' },
        paddingRight: { value: 16, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#64748b',
        borderRadius: { value: 20, unit: 'px' },
        fontSize: { value: 14, unit: 'px' },
      },
      children: [],
      parentId: 'categories',
      events: [],
    },
    'catHome': {
      id: 'catHome',
      type: 'Button',
      name: 'Home',
      props: { label: 'Home & Garden', variant: 'ghost' },
      styles: {
        padding: { value: 8, unit: 'px' },
        paddingLeft: { value: 16, unit: 'px' },
        paddingRight: { value: 16, unit: 'px' },
        backgroundColor: 'transparent',
        color: '#64748b',
        borderRadius: { value: 20, unit: 'px' },
        fontSize: { value: 14, unit: 'px' },
      },
      children: [],
      parentId: 'categories',
      events: [],
    },
    'sortSelect': {
      id: 'sortSelect',
      type: 'Select',
      name: 'Sort',
      props: { placeholder: 'Sort by', options: ['Price: Low to High', 'Price: High to Low', 'Newest'] },
      styles: {
        width: { value: 180, unit: 'px' },
      },
      children: [],
      parentId: 'filterBar',
      events: [],
    },
    'productsGrid': {
      id: 'productsGrid',
      type: 'Grid',
      name: 'Products Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: { value: 24, unit: 'px' },
      },
      children: ['product1', 'product2', 'product3', 'product4'],
      parentId: 'root',
      events: [],
    },
    'product1': {
      id: 'product1',
      type: 'Card',
      name: 'Product Card',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        overflow: 'hidden',
        boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      },
      children: ['product1Image', 'product1Content'],
      parentId: 'productsGrid',
      events: [],
    },
    'product1Image': {
      id: 'product1Image',
      type: 'Frame',
      name: 'Product Image',
      props: {},
      styles: {
        width: { value: 100, unit: '%' },
        height: { value: 200, unit: 'px' },
        backgroundColor: '#e2e8f0',
      },
      children: [],
      parentId: 'product1',
      events: [],
    },
    'product1Content': {
      id: 'product1Content',
      type: 'Frame',
      name: 'Product Content',
      props: {},
      styles: {
        padding: { value: 16, unit: 'px' },
      },
      children: ['product1Name', 'product1PriceRow', 'product1Btn'],
      parentId: 'product1',
      events: [],
    },
    'product1Name': {
      id: 'product1Name',
      type: 'Heading',
      name: 'Name',
      props: { content: 'Wireless Headphones', level: 'h3' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'product1Content',
      events: [],
    },
    'product1PriceRow': {
      id: 'product1PriceRow',
      type: 'HStack',
      name: 'Price Row',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: ['product1Price', 'product1Rating'],
      parentId: 'product1Content',
      events: [],
    },
    'product1Price': {
      id: 'product1Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$149.99' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'product1PriceRow',
      events: [],
    },
    'product1Rating': {
      id: 'product1Rating',
      type: 'Text',
      name: 'Rating',
      props: { content: '★ 4.8' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#f59e0b',
      },
      children: [],
      parentId: 'product1PriceRow',
      events: [],
    },
    'product1Btn': {
      id: 'product1Btn',
      type: 'Button',
      name: 'Add to Cart',
      props: { label: 'Add to Cart', variant: 'primary' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 10, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'product1Content',
      events: [],
    },
    'product2': {
      id: 'product2',
      type: 'Card',
      name: 'Product Card',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        overflow: 'hidden',
        boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      },
      children: ['product2Image', 'product2Content'],
      parentId: 'productsGrid',
      events: [],
    },
    'product2Image': {
      id: 'product2Image',
      type: 'Frame',
      name: 'Product Image',
      props: {},
      styles: {
        width: { value: 100, unit: '%' },
        height: { value: 200, unit: 'px' },
        backgroundColor: '#e2e8f0',
      },
      children: [],
      parentId: 'product2',
      events: [],
    },
    'product2Content': {
      id: 'product2Content',
      type: 'Frame',
      name: 'Product Content',
      props: {},
      styles: {
        padding: { value: 16, unit: 'px' },
      },
      children: ['product2Name', 'product2PriceRow', 'product2Btn'],
      parentId: 'product2',
      events: [],
    },
    'product2Name': {
      id: 'product2Name',
      type: 'Heading',
      name: 'Name',
      props: { content: 'Smart Watch Pro', level: 'h3' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'product2Content',
      events: [],
    },
    'product2PriceRow': {
      id: 'product2PriceRow',
      type: 'HStack',
      name: 'Price Row',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: ['product2Price', 'product2Rating'],
      parentId: 'product2Content',
      events: [],
    },
    'product2Price': {
      id: 'product2Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$299.99' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'product2PriceRow',
      events: [],
    },
    'product2Rating': {
      id: 'product2Rating',
      type: 'Text',
      name: 'Rating',
      props: { content: '★ 4.9' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#f59e0b',
      },
      children: [],
      parentId: 'product2PriceRow',
      events: [],
    },
    'product2Btn': {
      id: 'product2Btn',
      type: 'Button',
      name: 'Add to Cart',
      props: { label: 'Add to Cart', variant: 'primary' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 10, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'product2Content',
      events: [],
    },
    'product3': {
      id: 'product3',
      type: 'Card',
      name: 'Product Card',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        overflow: 'hidden',
        boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      },
      children: ['product3Image', 'product3Content'],
      parentId: 'productsGrid',
      events: [],
    },
    'product3Image': {
      id: 'product3Image',
      type: 'Frame',
      name: 'Product Image',
      props: {},
      styles: {
        width: { value: 100, unit: '%' },
        height: { value: 200, unit: 'px' },
        backgroundColor: '#e2e8f0',
      },
      children: [],
      parentId: 'product3',
      events: [],
    },
    'product3Content': {
      id: 'product3Content',
      type: 'Frame',
      name: 'Product Content',
      props: {},
      styles: {
        padding: { value: 16, unit: 'px' },
      },
      children: ['product3Name', 'product3PriceRow', 'product3Btn'],
      parentId: 'product3',
      events: [],
    },
    'product3Name': {
      id: 'product3Name',
      type: 'Heading',
      name: 'Name',
      props: { content: 'Laptop Backpack', level: 'h3' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'product3Content',
      events: [],
    },
    'product3PriceRow': {
      id: 'product3PriceRow',
      type: 'HStack',
      name: 'Price Row',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: ['product3Price', 'product3Rating'],
      parentId: 'product3Content',
      events: [],
    },
    'product3Price': {
      id: 'product3Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$79.99' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'product3PriceRow',
      events: [],
    },
    'product3Rating': {
      id: 'product3Rating',
      type: 'Text',
      name: 'Rating',
      props: { content: '★ 4.6' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#f59e0b',
      },
      children: [],
      parentId: 'product3PriceRow',
      events: [],
    },
    'product3Btn': {
      id: 'product3Btn',
      type: 'Button',
      name: 'Add to Cart',
      props: { label: 'Add to Cart', variant: 'primary' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 10, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'product3Content',
      events: [],
    },
    'product4': {
      id: 'product4',
      type: 'Card',
      name: 'Product Card',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 12, unit: 'px' },
        overflow: 'hidden',
        boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      },
      children: ['product4Image', 'product4Content'],
      parentId: 'productsGrid',
      events: [],
    },
    'product4Image': {
      id: 'product4Image',
      type: 'Frame',
      name: 'Product Image',
      props: {},
      styles: {
        width: { value: 100, unit: '%' },
        height: { value: 200, unit: 'px' },
        backgroundColor: '#e2e8f0',
      },
      children: [],
      parentId: 'product4',
      events: [],
    },
    'product4Content': {
      id: 'product4Content',
      type: 'Frame',
      name: 'Product Content',
      props: {},
      styles: {
        padding: { value: 16, unit: 'px' },
      },
      children: ['product4Name', 'product4PriceRow', 'product4Btn'],
      parentId: 'product4',
      events: [],
    },
    'product4Name': {
      id: 'product4Name',
      type: 'Heading',
      name: 'Name',
      props: { content: 'USB-C Hub', level: 'h3' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        marginBottom: { value: 8, unit: 'px' },
      },
      children: [],
      parentId: 'product4Content',
      events: [],
    },
    'product4PriceRow': {
      id: 'product4PriceRow',
      type: 'HStack',
      name: 'Price Row',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: { value: 12, unit: 'px' },
      },
      children: ['product4Price', 'product4Rating'],
      parentId: 'product4Content',
      events: [],
    },
    'product4Price': {
      id: 'product4Price',
      type: 'Text',
      name: 'Price',
      props: { content: '$49.99' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
      },
      children: [],
      parentId: 'product4PriceRow',
      events: [],
    },
    'product4Rating': {
      id: 'product4Rating',
      type: 'Text',
      name: 'Rating',
      props: { content: '★ 4.7' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#f59e0b',
      },
      children: [],
      parentId: 'product4PriceRow',
      events: [],
    },
    'product4Btn': {
      id: 'product4Btn',
      type: 'Button',
      name: 'Add to Cart',
      props: { label: 'Add to Cart', variant: 'primary' },
      styles: {
        width: { value: 100, unit: '%' },
        padding: { value: 10, unit: 'px' },
        backgroundColor: '#0f172a',
        color: '#ffffff',
        borderRadius: { value: 6, unit: 'px' },
        fontWeight: 500,
      },
      children: [],
      parentId: 'product4Content',
      events: [],
    },
  },
};

// ============================================================================
// Testimonials Template
// ============================================================================

export const testimonials: Template = {
  id: 'template_testimonials',
  name: 'Testimonials Section',
  description: 'A testimonials section with customer reviews',
  category: 'content',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['testimonials', 'reviews', 'social proof', 'marketing'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'Testimonials Section',
      props: {},
      styles: {
        padding: { value: 80, unit: 'px' },
        backgroundColor: '#ffffff',
      },
      children: ['header', 'testimonialsGrid'],
      parentId: null,
      events: [],
    },
    'header': {
      id: 'header',
      type: 'Frame',
      name: 'Header',
      props: {},
      styles: {
        textAlign: 'center',
        marginBottom: { value: 48, unit: 'px' },
      },
      children: ['title', 'subtitle'],
      parentId: 'root',
      events: [],
    },
    'title': {
      id: 'title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'What our customers say', level: 'h2' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'subtitle': {
      id: 'subtitle',
      type: 'Paragraph',
      name: 'Subtitle',
      props: { content: 'Trusted by thousands of developers and companies worldwide' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'testimonialsGrid': {
      id: 'testimonialsGrid',
      type: 'Grid',
      name: 'Testimonials Grid',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: { value: 32, unit: 'px' },
        maxWidth: { value: 1200, unit: 'px' },
        margin: { value: 0, unit: 'auto' },
      },
      children: ['testimonial1', 'testimonial2', 'testimonial3'],
      parentId: 'root',
      events: [],
    },
    'testimonial1': {
      id: 'testimonial1',
      type: 'Card',
      name: 'Testimonial 1',
      props: {},
      styles: {
        padding: { value: 32, unit: 'px' },
        backgroundColor: '#f8fafc',
        borderRadius: { value: 12, unit: 'px' },
      },
      children: ['t1Stars', 't1Quote', 't1Author'],
      parentId: 'testimonialsGrid',
      events: [],
    },
    't1Stars': {
      id: 't1Stars',
      type: 'Text',
      name: 'Stars',
      props: { content: '★★★★★' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        color: '#f59e0b',
        marginBottom: { value: 16, unit: 'px' },
        display: 'block',
      },
      children: [],
      parentId: 'testimonial1',
      events: [],
    },
    't1Quote': {
      id: 't1Quote',
      type: 'Paragraph',
      name: 'Quote',
      props: { content: '"PhilJS has completely transformed how we build applications. The developer experience is unmatched and the performance is incredible."' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        color: '#374151',
        lineHeight: { value: 1.7, unit: 'none' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'testimonial1',
      events: [],
    },
    't1Author': {
      id: 't1Author',
      type: 'HStack',
      name: 'Author',
      props: {},
      styles: {
        display: 'flex',
        alignItems: 'center',
        gap: { value: 12, unit: 'px' },
      },
      children: ['t1Avatar', 't1AuthorInfo'],
      parentId: 'testimonial1',
      events: [],
    },
    't1Avatar': {
      id: 't1Avatar',
      type: 'Frame',
      name: 'Avatar',
      props: {},
      styles: {
        width: { value: 48, unit: 'px' },
        height: { value: 48, unit: 'px' },
        borderRadius: { value: 24, unit: 'px' },
        backgroundColor: '#ddd6fe',
      },
      children: [],
      parentId: 't1Author',
      events: [],
    },
    't1AuthorInfo': {
      id: 't1AuthorInfo',
      type: 'Frame',
      name: 'Author Info',
      props: {},
      styles: {},
      children: ['t1AuthorName', 't1AuthorRole'],
      parentId: 't1Author',
      events: [],
    },
    't1AuthorName': {
      id: 't1AuthorName',
      type: 'Text',
      name: 'Name',
      props: { content: 'Sarah Johnson' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 't1AuthorInfo',
      events: [],
    },
    't1AuthorRole': {
      id: 't1AuthorRole',
      type: 'Text',
      name: 'Role',
      props: { content: 'CTO at TechCorp' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
      },
      children: [],
      parentId: 't1AuthorInfo',
      events: [],
    },
    'testimonial2': {
      id: 'testimonial2',
      type: 'Card',
      name: 'Testimonial 2',
      props: {},
      styles: {
        padding: { value: 32, unit: 'px' },
        backgroundColor: '#f8fafc',
        borderRadius: { value: 12, unit: 'px' },
      },
      children: ['t2Stars', 't2Quote', 't2Author'],
      parentId: 'testimonialsGrid',
      events: [],
    },
    't2Stars': {
      id: 't2Stars',
      type: 'Text',
      name: 'Stars',
      props: { content: '★★★★★' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        color: '#f59e0b',
        marginBottom: { value: 16, unit: 'px' },
        display: 'block',
      },
      children: [],
      parentId: 'testimonial2',
      events: [],
    },
    't2Quote': {
      id: 't2Quote',
      type: 'Paragraph',
      name: 'Quote',
      props: { content: '"We migrated from React and saw a 40% improvement in performance. The learning curve was minimal and our team was productive within days."' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        color: '#374151',
        lineHeight: { value: 1.7, unit: 'none' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'testimonial2',
      events: [],
    },
    't2Author': {
      id: 't2Author',
      type: 'HStack',
      name: 'Author',
      props: {},
      styles: {
        display: 'flex',
        alignItems: 'center',
        gap: { value: 12, unit: 'px' },
      },
      children: ['t2Avatar', 't2AuthorInfo'],
      parentId: 'testimonial2',
      events: [],
    },
    't2Avatar': {
      id: 't2Avatar',
      type: 'Frame',
      name: 'Avatar',
      props: {},
      styles: {
        width: { value: 48, unit: 'px' },
        height: { value: 48, unit: 'px' },
        borderRadius: { value: 24, unit: 'px' },
        backgroundColor: '#bfdbfe',
      },
      children: [],
      parentId: 't2Author',
      events: [],
    },
    't2AuthorInfo': {
      id: 't2AuthorInfo',
      type: 'Frame',
      name: 'Author Info',
      props: {},
      styles: {},
      children: ['t2AuthorName', 't2AuthorRole'],
      parentId: 't2Author',
      events: [],
    },
    't2AuthorName': {
      id: 't2AuthorName',
      type: 'Text',
      name: 'Name',
      props: { content: 'Michael Chen' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 't2AuthorInfo',
      events: [],
    },
    't2AuthorRole': {
      id: 't2AuthorRole',
      type: 'Text',
      name: 'Role',
      props: { content: 'Lead Developer at StartupX' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
      },
      children: [],
      parentId: 't2AuthorInfo',
      events: [],
    },
    'testimonial3': {
      id: 'testimonial3',
      type: 'Card',
      name: 'Testimonial 3',
      props: {},
      styles: {
        padding: { value: 32, unit: 'px' },
        backgroundColor: '#f8fafc',
        borderRadius: { value: 12, unit: 'px' },
      },
      children: ['t3Stars', 't3Quote', 't3Author'],
      parentId: 'testimonialsGrid',
      events: [],
    },
    't3Stars': {
      id: 't3Stars',
      type: 'Text',
      name: 'Stars',
      props: { content: '★★★★★' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        color: '#f59e0b',
        marginBottom: { value: 16, unit: 'px' },
        display: 'block',
      },
      children: [],
      parentId: 'testimonial3',
      events: [],
    },
    't3Quote': {
      id: 't3Quote',
      type: 'Paragraph',
      name: 'Quote',
      props: { content: '"The component library saved us months of development time. Everything just works together perfectly out of the box."' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        color: '#374151',
        lineHeight: { value: 1.7, unit: 'none' },
        marginBottom: { value: 24, unit: 'px' },
      },
      children: [],
      parentId: 'testimonial3',
      events: [],
    },
    't3Author': {
      id: 't3Author',
      type: 'HStack',
      name: 'Author',
      props: {},
      styles: {
        display: 'flex',
        alignItems: 'center',
        gap: { value: 12, unit: 'px' },
      },
      children: ['t3Avatar', 't3AuthorInfo'],
      parentId: 'testimonial3',
      events: [],
    },
    't3Avatar': {
      id: 't3Avatar',
      type: 'Frame',
      name: 'Avatar',
      props: {},
      styles: {
        width: { value: 48, unit: 'px' },
        height: { value: 48, unit: 'px' },
        borderRadius: { value: 24, unit: 'px' },
        backgroundColor: '#bbf7d0',
      },
      children: [],
      parentId: 't3Author',
      events: [],
    },
    't3AuthorInfo': {
      id: 't3AuthorInfo',
      type: 'Frame',
      name: 'Author Info',
      props: {},
      styles: {},
      children: ['t3AuthorName', 't3AuthorRole'],
      parentId: 't3Author',
      events: [],
    },
    't3AuthorName': {
      id: 't3AuthorName',
      type: 'Text',
      name: 'Name',
      props: { content: 'Emily Rodriguez' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
        display: 'block',
      },
      children: [],
      parentId: 't3AuthorInfo',
      events: [],
    },
    't3AuthorRole': {
      id: 't3AuthorRole',
      type: 'Text',
      name: 'Role',
      props: { content: 'Product Manager at DesignCo' },
      styles: {
        fontSize: { value: 14, unit: 'px' },
        color: '#64748b',
        display: 'block',
      },
      children: [],
      parentId: 't3AuthorInfo',
      events: [],
    },
  },
};

// ============================================================================
// FAQ Template
// ============================================================================

export const faqSection: Template = {
  id: 'template_faq',
  name: 'FAQ Section',
  description: 'A frequently asked questions section with accordion',
  category: 'content',
  version: '1.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  author: 'PhilJS',
  tags: ['faq', 'questions', 'accordion', 'support'],
  rootId: 'root',
  nodes: {
    'root': {
      id: 'root',
      type: 'Frame',
      name: 'FAQ Section',
      props: {},
      styles: {
        padding: { value: 80, unit: 'px' },
        backgroundColor: '#f8fafc',
      },
      children: ['header', 'faqContainer'],
      parentId: null,
      events: [],
    },
    'header': {
      id: 'header',
      type: 'Frame',
      name: 'Header',
      props: {},
      styles: {
        textAlign: 'center',
        marginBottom: { value: 48, unit: 'px' },
      },
      children: ['title', 'subtitle'],
      parentId: 'root',
      events: [],
    },
    'title': {
      id: 'title',
      type: 'Heading',
      name: 'Title',
      props: { content: 'Frequently Asked Questions', level: 'h2' },
      styles: {
        fontSize: { value: 36, unit: 'px' },
        fontWeight: 700,
        color: '#0f172a',
        marginBottom: { value: 16, unit: 'px' },
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'subtitle': {
      id: 'subtitle',
      type: 'Paragraph',
      name: 'Subtitle',
      props: { content: 'Find answers to the most common questions about our product' },
      styles: {
        fontSize: { value: 18, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'header',
      events: [],
    },
    'faqContainer': {
      id: 'faqContainer',
      type: 'Frame',
      name: 'FAQ Container',
      props: {},
      styles: {
        maxWidth: { value: 800, unit: 'px' },
        margin: { value: 0, unit: 'auto' },
      },
      children: ['faq1', 'faq2', 'faq3', 'faq4'],
      parentId: 'root',
      events: [],
    },
    'faq1': {
      id: 'faq1',
      type: 'Card',
      name: 'FAQ Item',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        marginBottom: { value: 16, unit: 'px' },
        overflow: 'hidden',
      },
      children: ['faq1Question', 'faq1Answer'],
      parentId: 'faqContainer',
      events: [],
    },
    'faq1Question': {
      id: 'faq1Question',
      type: 'HStack',
      name: 'Question',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 20, unit: 'px' },
        cursor: 'pointer',
      },
      children: ['faq1QuestionText', 'faq1Icon'],
      parentId: 'faq1',
      events: [],
    },
    'faq1QuestionText': {
      id: 'faq1QuestionText',
      type: 'Text',
      name: 'Question Text',
      props: { content: 'How do I get started with PhilJS?' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
      },
      children: [],
      parentId: 'faq1Question',
      events: [],
    },
    'faq1Icon': {
      id: 'faq1Icon',
      type: 'Text',
      name: 'Icon',
      props: { content: '+' },
      styles: {
        fontSize: { value: 24, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'faq1Question',
      events: [],
    },
    'faq1Answer': {
      id: 'faq1Answer',
      type: 'Paragraph',
      name: 'Answer',
      props: { content: 'Getting started is easy! Simply install the package via npm or yarn, and follow our quick start guide. You can have your first application running in under 5 minutes.' },
      styles: {
        padding: { value: 20, unit: 'px' },
        paddingTop: { value: 0, unit: 'px' },
        fontSize: { value: 15, unit: 'px' },
        color: '#64748b',
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'faq1',
      events: [],
    },
    'faq2': {
      id: 'faq2',
      type: 'Card',
      name: 'FAQ Item',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        marginBottom: { value: 16, unit: 'px' },
        overflow: 'hidden',
      },
      children: ['faq2Question', 'faq2Answer'],
      parentId: 'faqContainer',
      events: [],
    },
    'faq2Question': {
      id: 'faq2Question',
      type: 'HStack',
      name: 'Question',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 20, unit: 'px' },
        cursor: 'pointer',
      },
      children: ['faq2QuestionText', 'faq2Icon'],
      parentId: 'faq2',
      events: [],
    },
    'faq2QuestionText': {
      id: 'faq2QuestionText',
      type: 'Text',
      name: 'Question Text',
      props: { content: 'Is PhilJS suitable for large-scale applications?' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
      },
      children: [],
      parentId: 'faq2Question',
      events: [],
    },
    'faq2Icon': {
      id: 'faq2Icon',
      type: 'Text',
      name: 'Icon',
      props: { content: '+' },
      styles: {
        fontSize: { value: 24, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'faq2Question',
      events: [],
    },
    'faq2Answer': {
      id: 'faq2Answer',
      type: 'Paragraph',
      name: 'Answer',
      props: { content: 'Absolutely! PhilJS is designed to scale. We use fine-grained reactivity which ensures excellent performance even with thousands of reactive nodes. Many enterprise applications are built with PhilJS.' },
      styles: {
        padding: { value: 20, unit: 'px' },
        paddingTop: { value: 0, unit: 'px' },
        fontSize: { value: 15, unit: 'px' },
        color: '#64748b',
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'faq2',
      events: [],
    },
    'faq3': {
      id: 'faq3',
      type: 'Card',
      name: 'FAQ Item',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        marginBottom: { value: 16, unit: 'px' },
        overflow: 'hidden',
      },
      children: ['faq3Question', 'faq3Answer'],
      parentId: 'faqContainer',
      events: [],
    },
    'faq3Question': {
      id: 'faq3Question',
      type: 'HStack',
      name: 'Question',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 20, unit: 'px' },
        cursor: 'pointer',
      },
      children: ['faq3QuestionText', 'faq3Icon'],
      parentId: 'faq3',
      events: [],
    },
    'faq3QuestionText': {
      id: 'faq3QuestionText',
      type: 'Text',
      name: 'Question Text',
      props: { content: 'What about TypeScript support?' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
      },
      children: [],
      parentId: 'faq3Question',
      events: [],
    },
    'faq3Icon': {
      id: 'faq3Icon',
      type: 'Text',
      name: 'Icon',
      props: { content: '+' },
      styles: {
        fontSize: { value: 24, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'faq3Question',
      events: [],
    },
    'faq3Answer': {
      id: 'faq3Answer',
      type: 'Paragraph',
      name: 'Answer',
      props: { content: 'PhilJS is built with TypeScript from the ground up. You get full type inference, autocompletion, and type checking out of the box. No additional configuration needed.' },
      styles: {
        padding: { value: 20, unit: 'px' },
        paddingTop: { value: 0, unit: 'px' },
        fontSize: { value: 15, unit: 'px' },
        color: '#64748b',
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'faq3',
      events: [],
    },
    'faq4': {
      id: 'faq4',
      type: 'Card',
      name: 'FAQ Item',
      props: {},
      styles: {
        backgroundColor: '#ffffff',
        borderRadius: { value: 8, unit: 'px' },
        marginBottom: { value: 16, unit: 'px' },
        overflow: 'hidden',
      },
      children: ['faq4Question', 'faq4Answer'],
      parentId: 'faqContainer',
      events: [],
    },
    'faq4Question': {
      id: 'faq4Question',
      type: 'HStack',
      name: 'Question',
      props: {},
      styles: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: { value: 20, unit: 'px' },
        cursor: 'pointer',
      },
      children: ['faq4QuestionText', 'faq4Icon'],
      parentId: 'faq4',
      events: [],
    },
    'faq4QuestionText': {
      id: 'faq4QuestionText',
      type: 'Text',
      name: 'Question Text',
      props: { content: 'Do you offer enterprise support?' },
      styles: {
        fontSize: { value: 16, unit: 'px' },
        fontWeight: 600,
        color: '#0f172a',
      },
      children: [],
      parentId: 'faq4Question',
      events: [],
    },
    'faq4Icon': {
      id: 'faq4Icon',
      type: 'Text',
      name: 'Icon',
      props: { content: '+' },
      styles: {
        fontSize: { value: 24, unit: 'px' },
        color: '#64748b',
      },
      children: [],
      parentId: 'faq4Question',
      events: [],
    },
    'faq4Answer': {
      id: 'faq4Answer',
      type: 'Paragraph',
      name: 'Answer',
      props: { content: 'Yes, we offer enterprise support plans with dedicated support, custom SLAs, training, and consulting services. Contact our sales team for more information.' },
      styles: {
        padding: { value: 20, unit: 'px' },
        paddingTop: { value: 0, unit: 'px' },
        fontSize: { value: 15, unit: 'px' },
        color: '#64748b',
        lineHeight: { value: 1.6, unit: 'none' },
      },
      children: [],
      parentId: 'faq4',
      events: [],
    },
  },
};

// ============================================================================
// Export All Templates
// ============================================================================

export const additionalBuiltInTemplates: Template[] = [
  dashboardSidebar,
  landingPageSimple,
  navigationHeader,
  pricingTable,
  loginForm,
  blogArticle,
  productGrid,
  testimonials,
  faqSection,
];

export default additionalBuiltInTemplates;
